KC3Kai/KC3Kai

src/pages/panel/classes/Dashboard.js
I found https://kancolletool.github.io/docs/api/
Grinding 2-1 and 2-4 to confirm
Also temporarily changed
`$("#compassModal .enemyFleet").html("<img src=\""+iconFile+"\" /> "+nodeData.api_itemget.api_getcount);`
to
`$("#compassModal .enemyFleet").html("<img src=\""+iconFile+"\" /> "+nodeData.api_itemget.api_icon_id);`
Only managed to took this one screenshot and even forgot to change it back tho lol
=> [Fix #63] [Fix #106] Missing Consumables Icon on Compass Results Popup

src/pages/panel/classes/Dashboard.js
Fixed #105 
@dragonjet 
I tried to investigate a bit and found this nodeData is returned before going into the maelstrom node. I want to help you a bit so I made an attempt to fix this bug by myself.
{
"api_rashin_flg"    : 1,
"api_rashin_id"     : 3,
"api_maparea_id"    : 4,
"api_mapinfo_no"    : 3,
"api_no"            : 6,
"api_color_no"      : 3,
"api_event_id"      : 3,
"api_event_kind"    : 0,
"api_next"          : 1,
"api_bosscell_no"   : 13,
"api_bosscomp"      : 1,
"api_comment_kind"  : 0,
"api_production_kind":0,
"api_happening"     : {
"api_type":1,
"api_count":20,
"api_usemst":4,
"api_mst_id":2,
"api_icon_id":2,
"api_dentan":0
}
}
I am an oversea teitoku, who had a chance to use KanCo! Tools made by you long time ago. I was quite impressed by your work for the community and now …
=> [Fix #105] [Bug report] Compass Result: Showing previous result if the next node is a maelstrom

src/pages/strategy/tabs/TabShips.js
Since tooltips for the ship equipment was added to the panel, I thought maybe it should be added to the strategy room ship library so it would be a similar user experience.
=> Equipment Tooltips for Equipment in Strategy Ship Library

src/library/classes/Battle.js
Fix #131 
Check if the fleet is not unlocked.
It seems that when the fleet is not unlocked, it is not passed in the api_data. So instead of always sending all four fleets' information, it could send just 2 or 3 fleets, which causes the "undefined" of thisFleet.
=> [Fix #131] Sortie History Cannot Update

src/pages/panel/themes/horizontal.html, src/pages/panel/views/Dashboard.Fleet.js
I hacked the extension a little bit to show a list of expedition tasks current fleet might be able to do.
Some warning info is also included indicating the morale status and whether bullet and fuel are full.
Please see the screenshot.
I'm not proficient at web app development and sorry for not being able to make it look better.
For now only Expedition#1 ~ Expedition#24 are supported, I'm still new to KanColle so some of these expedition predicates are yet to be verified.
I still need some free time finishing up supports for the remaining expedition tasks,
just opening an early PR to see if you like this feature :)
=> New feature: adding expedition task helper

src/pages/panel/themes/horizontal.html, src/pages/panel/views/Dashboard.Fleet.js
A followup of #133, all predicates are implemented now (except for 33 & 34)
Just one question on [this line](https://github.com/dragonjet/KC3Kai/compare/dragonjet:master...Javran:exp-helper?expand=1#diff-99ab012a63a587b1109cabc0782a8e81R182) (src/pages/panel/views/Dashboard.Fleet.js, line 182):
is CT the correct `stype` for Katori?
=> Adding expedition helper (2)

src/library/classes/Assets.js, src/pages/panel/classes/Dashboard.js, src/pages/panel/panel.css, src/pages/panel/panel.html
I noticed after moving the Abyssal images to photobucket, the compass cannot show the enemy fleet image anymore so I made a fix for it. Now it looks like this.
=> [Fix] Compass result for enemy fleet doesn't work

src/pages/panel/classes/Dashboard.js
Previously, before adding the class "good" or "bad" to change the color of the text, I forgot to remove them out so the "Air Supremacy" sometimes can have the red color (instead of green) if the air battle was bad in the previous battle xD
=> Fix bug show color in BattleModal

src/library/modules/Kcsapi.js
Fix #188
Sorry for no video but it works for me now. The chosen ships still disappear regardless success or failure. Feel free to report if the issue still happens.
=> [Fix #188] BETA Ship on KC3Kai panel bugged

src/pages/devtools/themes/default/vertical/vertical.css, src/pages/devtools/themes/default/vertical/vertical.html, src/pages/devtools/themes/default/vertical/vertical.js
I just simply added more classes (e.g. big and small) into HTML and CSS. For now, it will force user to user big version of the layout but later we can add options to choose big or small. Just replacing `big` by `small` in HTML will work.
btw, could anyone having big screen use this version and send the picture to me? I don't have big screen and it's hard to imagine.
Normal Mode
Battle Mode (Single Fleet)
Battle Mode (Combined Fleet)
ps: this PR also fixed #209
=> [Feature] Increase the height of Vertical Layout

src/pages/devtools/themes/default/vertical/vertical.js
fixed for https://github.com/dragonjet/KC3Kai/issues/224 or rather https://github.com/dragonjet/KC3Kai/issues/188 for vertical. the exit battle mode is not fixed since too lazy to look at combined fleet code :sweat_smile: @bamboo3250 
added a color that if ship is being repaired, instead of red, the HP becomes blue, on vertical.js
=> Various fix

src/pages/devtools/themes/default/horizontal/horizontal.css, src/pages/devtools/themes/default/vertical/vertical.css
Fixed #227
Here I assume that the maximum number of ship slot never exceeds 999 and that of equip slot
never exceeds 9999.
__Vertical Layout (Small)__
__Vertical Layout (Big)__
__Horizontal Layout__
=> [Fix #227] [Bug report] Overlapping current equipment count and maximum equipment count when sortieing. #227

src/pages/devtools/themes/default/vertical/vertical.css
Fix #209
I added `white-space:nowrap;` to force it into only one line. Combining with `overflow:hidden;`, we solved the problem. :sparkles:
=> [Fix #209] Visual bug on Quest box overflow

src/data/translations/jp/terms.json
"AboutHelpCommunity" and "AboutHelpLearnMore" are translated.
=> [Translation: Japanese] [Terms] Adding new variables (2).

src/pages/settings/settings.css
Its font size, 16px, is too large for "保存する！" (Saved!) word for now.
=> "font-size" for ".settingBox .note" is prohibited.

src/library/modules/Kcsapi.js
=> [Fix #303] Remaining fuel and ammo not updated in resupply menu

src/library/objects/Quest.js, src/pages/devtools/themes/default/horizontal/horizontal.js, src/pages/devtools/themes/default/vertical/vertical.js
resolved #342 
* hide fulfilled conditions (except it's the last one), show the next "not-fulfilled" condition if available
* added tooltip for quest status and quest description in both `horizontal.js` and `vertical.js`
=> [Feature #342] Added tooltip for quest status and quest description

src/data/translations/jp/terms.json
Contain `SettingsHQExpDetail` (also its followers) and `SettingsPanelRequirement` now. (#458)
=> [Translation: Japanese] [Terms] Adding new variables (5).

src/data/translations/en/terms.json
`SettingsGearHolder` as "Gear Background Color", also `Black` and `White`.
=> [English] [Terms] Adding name for `SettingsGearHolder`.

src/pages/strategy/tabs/wikia/wikia.js
Minor fix required to prevent it from being "Chitose-A/" instead of "Chitose/A".
=> It was "-A" instead of " A" for Chitose-class remodels

src/library/modules/Kcsapi.js
When we navigate through the map list (`\mapinfo`), it will tell us the HP of the map is 9999 but then when we start the sortie (`\start`), it will show the true HP of the map. So this fix is to get the second one.
=> Update event map HP when starting sortie

src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.js
resolved #587 
Added tooltip for enemy ships, showing their FP, torpedo, AA and Armor
=> [Feature #587] [Suggestion] Add enemy flagship boss's armor stats.

src/assets/js/global.js, src/data/settings.json, src/library/managers/ConfigManager.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Cf. issue #748.
Everything seems to be working correctly, but there are a couple of places I'm not sure how we want to proceed.
1. Displaying the estimated time of completion for repairs currently doesn't play nice with repair times longer than 24 hours.  If it's 10 a.m. right now and Akagi needs 40 hours to repair, it'll just say "04:00" without specifying that it's 4 a.m. two days from now.
2. There is some potential ambiguity between duration and expected time of completion.  Currently what I have done is add a minus sign ("-02:30") to indicate remaining repair time and no such mark if time of day is being displayed instead.
3. Right now I'm displaying the current time when there are no repairs needed, but since the time display doesn't update as the clock ticks, it might look weird to …
=> Timer toggle

src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js
Adding invert selection for ship list
for example:
1. all ship types are selected by default
2. click "CA", "CAV"
3. every ship except "CA" and "CAV"
4. click "Invert"
5. "CA" and "CAV" only
=> invert selection for ship list

src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js
Adding a heartlock filter in ship list page.
could be one solution to #720
=> Adding a heartlock filter

src/pages/strategy/tabs/gears/gears.css, src/pages/strategy/tabs/gears/gears.html, src/pages/strategy/tabs/gears/gears.js
Added few buttons on equipment list, the list now can be sorted by stats
and these buttons are changed dynamically depending on equipment types and equipments available.
=> Adding stat sorters on equipment page

src/pages/strategy/tabs/expedpast/expedpast.js
sometimes there are errors accessing nonexist member and the loop breaks because of this...
=> fix drum count on expedition history page

src/library/managers/ConfigManager.js, src/library/objects/Gear.js
More accurate air power calculation: aircraft bombers and seaplane bombers don't share the bonus that fighers have, in `ConfigManager` I've splitted AP bonus table by gear types.
Data format changed:
* `ConfigManager.air_bounds`
* `ConfigManager.air_average`
Most seaplane bomber APs values are just guessing - all I know is the +9 bonus for double chevron ones. Until more accurate formula gets figured out, I think this is the best we can do.
References:
* http://wikiwiki.jp/kancolle/?%B4%CF%BA%DC%B5%A1%BD%CF%CE%FD%C5%D9
* http://zh.moegirl.org/%E8%88%B0%E9%98%9FCollection/%E8%88%B0%E8%BD%BD%E6%9C%BA%E7%86%9F%E7%BB%83%E5%BA%A6
* http://kancolle.wikia.com/wiki/Aircraft_Proficiency
=> fix air power calculation

src/pages/devtools/themes/natsuiro/natsuiro.js
=> fix deckbuilder export: use ace stat if available

src/pages/strategy/tabs/expcalc/expcalc.js
set image title to ship name + rosterid this can make it easier for newer players or ships that some of us don't recognize easily to be selected. Also increase max level to 155 per 12/8 kancolle release.
=> modification to leveling tab

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/Translation.js
implements #1036 
- when this option is enabled, ship type is always in English. (disabled by default)
- when `stype.json` is missing, the English version will be used (making `stype.json` in other languages optional)
=> Option for forcing English ship type

src/library/modules/Kcsapi.js, src/library/modules/RemodelDb.js, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/strategy/strategy.js, src/pages/strategy/tabs/mstship/mstship.html, src/pages/strategy/tabs/mstship/mstship.js
I have implemented a module called "RemodelDb", that computes everything related to remodeling (cost, required level, etc.) from `api_start2` data. devs can take a look.
As a byproduct of this. I added "other forms" in ship library. when a ship has forms other than herself and her next remodel, "Other forms" will appear. may need some tweak on UI afterwards xD.
Note that for this patch to work you need to start the game so RemodelDb can receive `api_start2`. (you only need to do this once)
=> "Other forms" in Ship Library

src/library/objects/Screenshot.js
* Detects `window.devicePixelRatio` and applies it to screenshot scales
* Would detect both retina (2dppx) and other high-density (1.3dppx etc)
=> Fix #49 Detect devicePixelRatio for screenshot

package.json, src/manifest.json, src/pages/game/api.js, src/pages/game/dmm.js, update
* Fix subtitle fade transparency applies to next quote
* Sync DMM page and API page subtitle fade scripts
* More subtitle quote fixes [from the sheet](https://docs.google.com/spreadsheets/d/1wg7pCv3l6g8BfOye3-DbrCuYDhTvSX4h1UuiRCp0_K8)
* Fix errors on languages without `quotes.json`
=> Release 28.1

src/library/modules/Meta.js, src/pages/game/api.js, src/pages/strategy/tabs/mstship/mstship.js, src/pages/strategy/tabs/mstupdate/mstupdate.js
For now...
* Separated usage of `api_version` array on card and voice
* Supports separated subtitle fade-out timing for each languages
=> Some fixes for game updates

src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/plain.js
Merging this PR will automatically close the following issues
* Close #960
A simple impl. for #960, on both sortie and PvP, show line on battle activity:
`Contact: <img>(or "None") vs <img>(or "None")` (image icon with title of plane name)
instead of former plain text.
Plane icon only half-size as line-height limited.
* Only available for natsuiro theme
* Not synced for plain theme and Strategy Room sortie history yet, history may left to 'Strategy Room enhancement'.
=> [dev-contact-plane] Show contact plane

src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/plain.js
Merging this PR will automatically close the following issues
* Close #1283
For #1283, I feel this workaround really easy to impl :joy: 
Of course better plan should be syncing profile data (including quest tracking status) via Chrome between devices.
This one just for convenience to avoid open Strategy Room when some opened quests completed at other place.
Usage: Click on the color box of quest at quest list of panel. Status will be toggled between 'open' and 'complete'. And when u go back to main port in-game, the completed ones will disappear.
As usual, if a quest not completed in fact, go to quest page in-game, it will be reopened again.
=> [dev-panel-toggle-quest] Toggle completion status of quest from panel

src/pages/devtools/themes/natsuiro/js/Shipbox.js, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/js/Shipbox.js
Close #1289
Dislike to calculate 25% hp manually for each ship either, so add a tool tip to current HP of ship list panel :sweat_smile: 
Hint by #1289 , add a left value too and only appear when Taiha HP < Current HP < Max HP.
BTW remove the duplicated AACI tool tip builder codes, commit it here...
=> Show Taiha HP left tooltip on panel

src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Continued for #1294 
Fix twice triggered AACI node issue.
And for @Javran and @dragonjet :
I've considered the way that show AACI indicator in ship box at first. But there are some design problems:
* Battle activity attach the data for current battle node only
* Shipbox list attach the data from player's fleets (showing current selected)
* Extra data for indicators have to be passed to Shipbox object (or every ship objects in Fleet array) and kept during the battle node completed. Otherwise the indicators would disappear if user click on other fleet and switch back (or other events re-render the shipbox)
* I add a extra attribute to ship object for the MVP icon, and do cleaning for each time battle node changed.
* DJ gonna to pass extra data to Shipbox define function to show Damecon …
=> [dev-show-aaci] Show AACI battle flag on panel #2

src/pages/devtools/themes/natsuiro/natsuiro.js
Another try to solve timers unexpected stopping related to #1279
As there's no way to restart, even inspect or check the existed browser timer object at all... the only way left is clear old one (if possible) and re-set a new one when timer stopped unexpectedly.
This time refactor the codes initializing and handling the Morale and UI updating timers. When go back to home port, automatically check if timer has not run for >2s, if true, reset it.
And this check is able to be triggered manually by clicking on morale timer on panel.
ps. applied to natsuiro theme only, not plain yet.
=> Refactor for unexpected timers freeze issue #1279

src/pages/strategy/tabs/overlodger/overlodger.js
Two things are misunderstood leading the issue:
* `totalBuffer` is supposed to order by its elements.id desc.
but push new elements (which are also order by id desc) to `totalBuffer` will break the order.
so just concat new elements (in front of all) with old totalBuffer (after the new ones).
* the first argument of `Range` sent to function `get_lodger_data` is supposed to be the latest ledger id in `totalBuffer`.
but `Object.keys(this.totalBuffer)` will return index array instead of elements.id array.
so just get the first element's id as long as previous order not broken.
@ReiFan49 could review it, I think this will solve it without breaking hour range check.
=> Fix overlodger start time issue

src/library/modules/Meta.js, src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Currently just show the kind of attack when support expedition triggered, like this:
| ICON |
| -------- |
|Support fleet 2 has arrived! |
|Fire attack support triggered! |
There're 3 types now: `Air/Fire/Torpedo`, able to be translated in `battle.json`.
=> Show more info at support attack flag icon tooltip

src/library/managers/ShipManager.js
this is only workaround to force every `sortie0` data to not appear anywhere around the sortie0 itself,
**you need to supply/repair the respective ship to remove the ghost entries**
- Attempt #1356
to test the data there are some steps that need to check:
1. find any ship with long entry of `lastSortie` data<br>(it's not a must for a global maximum length one, it can be more than one)
2. output the current state of `lastSortie` of the respective ship
3. perform supply and/or repair
4. output the last state of `lastSortie` of the respective ship
=> Local Storage Sortie Data Overquota

src/library/objects/StrategyTab.js, src/pages/strategy/strategy.css, src/pages/strategy/strategy.html, src/pages/strategy/strategy.js, src/pages/strategy/tabs/mstgear/mstgear.js, src/pages/strategy/tabs/mstship/mstship.js, src/pages/strategy/tabs/quotes/quotes.js
Close #1381 
The re-executed rendering and hash parameters handling problems has been realized when I tried to improve ship list page. It's not only the thingy about 'Ship Library', but an important mechanism all tab pages should rely on.
This time add a new term `update` to tab definition first, allowing each tab itself to decide if partially updating content required and how updating performed.
Currently `mstship`, `mstgear`, `quotes` supported,
More possible tabs: `ships`, `gears`, `fleet`, `aircraft`, `maps/event`
ps. performance of quotes tab is better by moving en/jp quotes loading into `reload` term.
=> [dev-sroom-update] Improve update mechanism of Strategy Room tab

src/library/modules/Database.js, src/library/objects/Node.js, src/pages/strategy/tabs/encounters/encounters.js
Close #1314
Related with #1139 
Changes:
* Upgrade encounters table schema of IndexedDB, improve adding functions
* Record difficulty for event nodes, name for all nodes. Build proper ID to compatible with normal maps
* Show map box `World 3x-m[E/N/H]` at Strategy Room encounters page
* Fix duplicated nodes of encounters page for #1314 
* Add a simple counter to each pattern
* Add enemy name (from `battleresult` API) to each node and formation
Known issue: existed data of encounters will still be shown without difficulty (in other map box), as there's no way to know which difficulty they are.
=> [dev-upgrade-encounters] Encounters record difficulty of event maps

src/library/objects/Fleet.js, src/library/objects/Gear.js, src/library/objects/Ship.js, src/pages/devtools/themes/natsuiro/js/Shipbox.js, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/js/Shipbox.js, src/pages/devtools/themes/plain/plain.js
Partially satisfy #1392
Just add tooltips to panel for selected fleet and every ships to show resupply cost (including bauxite).
Indeed supply consuming result shown at Activity panel not impl yet.
=> Show resupply costs

src/library/modules/Kcsapi.js
Fix  #1411
Add some codes to handle `api_req_quest/stop` API request to solve stopping quest at 'Active Quest Tab' issue.
=> [dev/quest-stop] Handle quest stop event

src/data/settings.json, src/library/managers/ConfigManager.js, src/pages/strategy/tabs/expcalc/expcalc.css, src/pages/strategy/tabs/expcalc/expcalc.js
**Problem** young teitoku got too many ships inside recommendations section. Can easily miss ship that can be remodelled or close to remodel.
**Solution**
- highlight with green colour ships that can be upgraded
- highlight with blue colour ships that are close to upgrade (lvl difference could be changed in settings)
[How it looks like in the end]( http://imgur.com/00gVjUI)
P.S. `"min" : 0` actually isn't working.
=> Highlight ships that are close to remodel or can be remodelled

src/pages/strategy/strategy.css, src/pages/strategy/tabs/ships/ships.css, src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js
* Added sparkle filter
* Added show/hide pages
* Updated UI
* Filter list decluttered
* Equipment slot count no black circle
* "Back to top" button does not cover bottom ships
=> [dev/sroom-shiplist] Ship List Update

src/pages/strategy/strategy.html, src/pages/strategy/tabs/compare/compare.css, src/pages/strategy/tabs/compare/compare.html, src/pages/strategy/tabs/compare/compare.js
* New Strategy Room tab: Compare Ships
* Can select any number of ships to compare their stats
* Highest stat highlighted in green, fades the color for lower stat ships
* Can switch stat views to get a bar graph of each ship's stats
=> [dev-compare] Compare Ships Feature

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/RemodelDb.js, src/pages/strategy/tabs/expcalc/expcalc.css, src/pages/strategy/tabs/expcalc/expcalc.html, src/pages/strategy/tabs/expcalc/expcalc.js
few improvements on leveling tab, also close #1445 
- remove blinking animation
- let RemodelDb help with goal level recommendation
this makes it possible to do things like recommending Lv 78 as a goal for Souryuu on Lv 31 
(you could have remodelled  Souryu to Souryuu Kai at Lv 30,
but in current master branch when the level goes beyond 30 there's no more recommendation)
- suggest updating current goal instead of removing a completed goal
when user is removing goals for ships that have not yet reached their final form,
pop up a dialog to ask user if they want to update goal to next recommended level
instead of removing the goal.
(example: removing Souryuu on Lv 31 when the goal level was Lv 30, ask user if they'd like
to change the goal to Lv 78)
- highlight color improvement (make color …
=> Leveling tab improvements

Gruntfile.js, src/assets/js/global.js, src/assets/js/no_ga.js, src/pages/popup/popup.html, src/pages/popup/popup.js
* Removed Google Analytics from Popup Menu (Gold Heart icon)
* Having GA there loads an external file which waits to be loaded before menu is shown. This makes is very long to show up for those with slower internet
* Having GA tracking on the menu breaks our average session time metric since menu is tracked but is opened and closed in a short period
* Removed Paypal pixel that is an external link, and will wait or it to be loaded before menu is shown. This won't be the case anymore.
=> Optimize menu: show instantly

src/assets/js/global.js, src/library/managers/PlayerManager.js, src/pages/strategy/tabs/docking/docking.js, src/pages/strategy/tabs/overlodger/overlodger.js
seems the Ledger is relying on `Math.stdev` for some calculation and I got an call stack overflow because of a long sortie history (~ 60000 elements). fixed by calling `Math.stdev([bool,] <an array>)` instead.
sorry for the noise in the diff view, the end of line gets messed up so I reindented them before working on this patch, the real changes are just 318796d and 39cd6ba .
I think @ReiFan49 is the original author of this part, could you take a look and see if this patch is good enough?
=> Prevent a call stack overflow when Math.stdev is called with too many arguments

src/data/settings.json, src/library/managers/ConfigManager.js, src/pages/popup/popup.js
addressing (reopened) #1535
added an option under "Global" part of the setting page, checked by default. this allows user to bypass DMM login requirement when un-checked.
btw the DMM login checking might have some problems, I always need to go to DMM website first before I can see 3 play options in the menu despite that I've logged in.
=> leaving DMM login enforcement an option

src/pages/strategy/tabs/gears/gears.html, src/pages/strategy/tabs/gears/gears.js
Right now the All items in Strategy Room > Equipment List page sorts the items by Sum. However, since they come from different equipment types, the order they show up doesn't make sense, and just makes it harder to look at.
This will add a new sort type, by equipment type, in the All category. If there are equipment from the same type, they will be sorted by the default comparator for that equipment type.
=> Add sort by type in all items in SR gear page

src/pages/strategy/tabs/event/event.html
Make an entry for Fall 2016 and make it default for the Event tab.
However I have also hidden the tab "Spring 2015", otherwise there are too many contents in a row and the layout overflows. Some extra work might be required for a more proper fix.
=> Fall 2016 history entry in strategy room

src/library/managers/SortieManager.js, src/library/modules/Kcsapi.js, src/library/modules/Meta.js, src/library/modules/Network.js, src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/strategy/sortielogs.js, src/pages/strategy/tabs/encounters/encounters.css, src/pages/strategy/tabs/encounters/encounters.js, src/pages/strategy/tabs/event/event.css, src/pages/strategy/tabs/maps/maps.css
Add processing chain as additional data attached to a node for Enemy Air Raid (in API `api_req_map/next@api_data.api_destruction_battle`) to show land-base air raid battle result in battle activity panel.
As it's in request `/next`, no persistence supported yet, will be not in sortie history.
And as it has conflicted with #1612, I've merge that first. So that will be also merged when this PR merged.
ps. panel screenshot like this:
=> Battle activity for Land-base Enemy Air Raid

src/library/modules/Meta.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/strategy/sortielogs.js, src/pages/strategy/tabs/encounters/encounters.css, src/pages/strategy/tabs/encounters/encounters.js, src/pages/strategy/tabs/event/event.css, src/pages/strategy/tabs/maps/maps.css
As discussion at #1500 . Implemented by adding CSS styles of `border-color` or `border-shadow`.
Supported colors:
* Princess / Demon: glow lightblue
* Kai: blue
* Flagship: golden
* Elite: crimson
Flagship & Elite is recognized by mater data `api_yomi`, but Kai / Bosses are not. Hard-coded IDs is current shortcoming. If devs add more abyssal ships, the ID list needs to be updated too.
Affected pages:
* natsuiro panel: battle activity
* SRoom: Map / Event history
* SRoom: Encounters
Feel free to adjust colors or styles for more clearly visual effect.
=> Add colored border to abyssal ship icons

src/library/modules/Meta.js, src/library/modules/Translation.js
Refactor ship name meta method, allow ship names translated and combined by 'prefixes + root + suffixes' model sourced from #1696. The prefixes & suffixes (and abyssal's 'yomi') are separated into individual JSON file in TL repo named `ship_affix.json` for easier updating works.
Not only for the seasonal ship names, but also benefited for more automatic ship name (including abyssal's maybe) translation to reduce the lines of `ships.json`. For example, `軽巡ツ級` may be defined as prefix `Light Cruiser ` + root `Tsu-Class`; `駆逐イ級後期型` may be defined as prefix `Destroyer ` + root `I-Class` + suffix ` Late Model`.
For @KC3Kai/translators, the rules of affixes replacement should be known:
* Lines of prefixes & suffixes table in `ship_affix.json` should be in correct order: 'first in first …
=> Ship name translation method improvement

src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.js
hover on resource / maelstrom nodes to see resource gain / loss on that node.
already tested on resource / maelstrom / bounty (1-6 N) nodes.
=> node tooltips for resource gain / loss

src/library/managers/SortieManager.js, src/library/objects/Fleet.js, src/library/objects/LandBase.js
Related to #1712. Updated `sortie` table, tested on my side.
* Add new LBAS array to record land base objects of sortied world only, and action: sortie or defend (maybe other actions also needed?)
* Add stars & ace for ship equipments including ex-slot (also fixed length array)
Next TODOs
* Fleet manager loading from sortie history could get stars & ace
* Maps/Events history could show LBAS up
* Calculate and show eLoS & air power of sortieing (the values at beginning only) for Maps/Events history
Not supports:
* eLoS and air power calculation for every Nodes at Maps History. As after each battle (even during one battle, different phase) need to be recalculated based on latest slot count and proficiency of planes, but we don't record the change of slots.
=> Update recording properties of sortie IndexDB

src/library/modules/Kcsapi.js, src/library/objects/Node.js
Although the ally gauge rate ranges may not be accurate by fully testing, as there is no night battle for LD Air Raid, I think it doesn't matter if prediction goes wrong. (tested on 6-4 ld_airbattle)
btw1: why it was not supported, see #1333 
btw2, rank predict for combined fleet (no matter which side) still not supported yet.
This PR main point is to recognize all the battle api call types on Node class side which hidden by re-invoking normal battle function on handling kcsapi (by adding a fake property `api_name` to API data)...
=> Support Long Distance Air Raid rank prediction

src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js
Implement #1690.
Added "GS Rate" together with some hint texts:
- only visible when "great success" toggle is on
- great success rate is only available when having >=4 sparkled ships in fleet (otherwise the text is always `???` because we lack an accurate estimation for this situation)
- the text turns golden when having >=4 sparked ships
- exceptions are expedition 21, 24, 37, 38, 40, for these expeditions we further require carrying sufficient drums before the text can turn golden.
=> expedition panel: great success condition checker

src/pages/devtools/themes/natsuiro/natsuiro.js
fix #1690. changes:
- show GS rate as `~99%` for expeditions that support extra drum when all GS conditions are met
- hide GS rate when expedition basic requirements are not met (resupply not considered)
=> expedition tab GS rate text fix

Gruntfile.js, src/library/managers/PlayerManager.js, src/library/modules/Kcsapi.js, src/library/modules/WhoCallsTheFleetDb.js, src/pages/strategy/tabs/akashi/akashi.css, src/pages/strategy/tabs/akashi/akashi.html, src/pages/strategy/tabs/akashi/akashi.js, src/pages/strategy/tabs/profile/profile.js, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
Related #1621 , #1183 , #944 and so on.
A simple improvement by importing WhoCallsTheFleetDb of items, thanks for @Diablohu first.
Features like a 'planner', 'scheduler' or 'simulator' not planned yet.
Screenshot for now (also added WhoCallsTheFleet link to FAQ) :
New screenshot for dark theme:
TODO:
* Required weekdays and ships not based on the DB, we still have to update `akashi.json`. Question: get rid of `akashi.json` or not?
=> Improvements of Strategy Room Akashi page

src/library/managers/QuestManager.js, src/library/objects/Quest.js
Try to handle quests which sharing single counter, esp those quests are able to be activated at same time. (which cause on 1 condition full-filled, progress +2 for all shared quests)
Currently just added Bd6 and Bd5 (`[218, 212]`) pair, more configs are expected.
iirc some 'submarine sunk' quests also sharing counter.
=> Tracking quests with shared counter

src/library/managers/SortieManager.js, src/library/modules/Kcsapi.js, src/library/objects/Fleet.js, src/library/objects/Node.js, src/library/objects/Ship.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Related to #1655, #1498, might be more.
Thanks to new game mechanism of LBAS and jet aircraft, the known fact that resources consumption for our Strategy Room ledger of these new stuffs are not correctly recorded yet. And unfortunately, these consumption are just counted at server-side, no any API data returned to client-side until player back to home port in game.
Known types of consumption not recorded for now:
* LBAS sortie fuel and ammo, amounts are researched and verified, but may change for future events
* LBAS losses of fuel or bauxite on enemy air raid, amount is verified but type is random
* Jet bomber steel
Based on many verifier's hard works, and the timing confirmation of #1733, we could complete these data recording step by step.
This PR TODOs:
* ~~Possible amount of loss on …
=> Update ledger DB recording

src/library/managers/PlayerManager.js, src/library/modules/Kcsapi.js, src/pages/strategy/tabs/profile/profile.css, src/pages/strategy/tabs/profile/profile.html, src/pages/strategy/tabs/profile/profile.js
This [old designed feature](https://github.com/KC3Kai/KC3Kai/blob/857f35e984bd50e136e70f3c55a033d15b68b879/src/pages/strategy/tabs/TabHome.js) is requested again... XD
Limited by API data, only the recent logs of news feed will be saved into local storage since last time back to home port in game.
Then list them up at Profile page of Strategy Room. Support translating messages into English based on type ID.
Profile SS:
Homeport SS:
(so why are there 6 lines in API? dunno... 😂 )
=> List up recent news feed

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/Kcsapi.js, src/library/modules/Network.js, src/library/objects/Fleet.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js
Natsuiro theme only, close #1454
* Add new setting to toggle activity
* Add new API handling
* Add two activities for PvP opponents list and fleet details
* Also show PvP create type
* Also show opponent's fleet name which is hidden in game
* Not show some values useless I think: friend count? exp of next level?
SS, styles are still being adjusted:
new SS with xp and formation:
Base EXP with rank & CT bonus:
=> Show PvP opponents info

src/data/settings.json, src/library/managers/ConfigManager.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Close #1480 this time.
Two new settings added:
* Disabled at Home Port, default: false. Enable it at player's own risk. Because it's one of two situations which should alert player NOT to go ahead with Taiha ship.
* Ignore Damecon Ship (in other world: Disabled if Damecon equipped), default: false
can not find any reason to show Taiha alert on PvP battle... so removed the unused term of TL.
I guess it was supposed to alert at Home Port to stop player sortieing for PvP if there is Taiha non-flagship.
(i'm wondering what is the English term to describe 'non-flagship ship' which referred to `僚艦` or `随伴艦` 🤔 )
=> Settings to disable Taiha alert

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/objects/Node.js, src/library/objects/Quest.js
- added `ConfigManager.spCounterAdjust`, default to `true`.
- when set `false`, recover old behavior that doesn't try to deal with shared quest counters
- new term added: `SettingsSpecialCounterAdjust`
@KC3Kai/translators see https://github.com/KC3Kai/kc3-translations/pull/379/files for examples. sorry that we don't really have room to explain this option properly, until things like #1468 can be done. so try to make a concise description.
=> Provide an option of disabling special quest adjustment

src/library/objects/Screenshot.js
as found by @DynamicSTOP while developing for showcase exporter in #1792
=> png-imgur/ substring(23) doesn't work with PNG

src/library/managers/ShipManager.js, src/library/objects/ShowcaseExporter.js, src/pages/strategy/strategy.html, src/pages/strategy/tabs/showcase/showcase.css, src/pages/strategy/tabs/showcase/showcase.html, src/pages/strategy/tabs/showcase/showcase.js
Two new buttons inside showcase tab. http://imgur.com/a/67gxg
Export are made in "download only" mode, because i am not sure that chrome will be ok about long data url. Though forcing it to use screenshot setting (imgur\download\new tab) or adding new one into options shouldn't be a big problem.
Would be really glad if someone could:
1. review code and point places that i should change (i am more like php developer and scopes in js makes me crasy)
2. test equip export. i am not even 1yo teitoku so i don't have a lot of rare stuff.
=> new ship\equip export tool on showcase page

src/data/settings.json, src/library/injections/dmm_takeover.js, src/library/managers/ConfigManager.js, src/library/objects/SettingsBox.js, src/pages/settings/settings.css, src/pages/settings/settings.html, src/pages/settings/settings.js
I didn't notice this previously, but now I feel the new idle timer is slightly on the annoying side: most of the time I just let the game open and all I need is just to have secretary ship in sight. and new idle timer ruins that by fading out the whole game screen. more importantly there is no way to officially cancel that - perhaps you can set a rather big number but that doesn't sound right to me.
that's all motivation for this PR, changes (pretty much copied from my commit log):
- ~~new setting box type: `number`~~ `small_text` turns out to be a better option
- ~~most of the code copied from `long_text`~~
- ~~no verification on field~~
- value is parsed and written back to UI upon change 
(btw the input value was never parsed in the original version so one could only hope the input (as …
=> Make it possible to disable idle timer

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/objects/Node.js, src/library/objects/Quest.js, tests/library/objects/Quest.html, tests/library/objects/Quest.js
an attempt to solve the quest counter auto adjusting problem once for all:
- detect both falling-behind and overshotting problems and try to correct them
- prevent an known incompleted quest from completion
- some unit tests included
I admit the code is a bit complicated, but in order to have every case covered, I feel it has to be.
please follow comments in code to see if my reasoning is clear to you.
and in case you are too lazy to read the code, I have also written some unit tests to demonstrate the expected behavior of this auto quest counter adjustment.
despite the fact that this PR is ready for reviewing, let's take our time and don't rush for approvals, as quest tracking is one of those important features, I wish this one can be good enough to replace the old one.
after this we may …
=> attempt for a smarter auto adjust counter

src/assets/js/global.js, src/library/managers/PlayerManager.js, src/library/managers/ShipManager.js, src/library/managers/SortieManager.js, src/library/modules/Kcsapi.js, src/library/objects/Node.js
As there are many codes changed, open a PR for more tests to check if I missed something or not.
~~No feature changed~~, just unify and refine time handling codes when timestamp converted to seconds or hours, and add time unit to vars name. 
At first, my motivation is the fix thingy. After double checking of each API handling, I have to clarify and explain the enhancement of feature: Keep tracking with game displaying for 8 basic materials (fuel, ammo, steel, bauxite, torch, bucket, devmat, screw), show their latest values in time and correctly at devtools panel.
*Long story*: as we know, there are 3 types of API call which would consume or gain materials:
1. In api_data of response, there is `api_materials` liked data to tell us all the absoluate values of materials the player hold.
we …
=> Fix time unit of API handling and refresh panel materials in time

src/pages/strategy/sortielogs.js
Implements #1901. Holding shift while clicking the replay button will directly open a new tab with that replay. 
Requires [kancolle-replay/#33](https://github.com/KC3Kai/kancolle-replay/pull/33) to work.
=> Export directly to battleplayer site while holding shift key

src/pages/strategy/tabs/profile/profile.html
Fix #1895
- comment out "Health Metric" section in FAQ because it's simply wrong or lack of an actual proof or at least some sorts of evidence. And because the section name "Sortie Statistics" (see bullet right below) pretty much explains itself we don't need a FAQ section for it.
- rename "Health Metric" to "Sortie Statistics", we should not put value to users and "Sortie Statistics" is a neutral name that I think most of us would agree on.
=> address #1895

src/library/managers/PlayerManager.js, src/library/modules/Kcsapi.js, src/library/objects/AkashiRepair.js, src/library/objects/Fleet.js, src/library/objects/Ship.js, src/pages/devtools/themes/default/default.html, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/plain.html, src/pages/devtools/themes/plain/plain.js, src/pages/strategy/strategy.html, tests/library/modules/BattlePrediction.html, tests/library/objects/AkashiRepair.html, tests/library/objects/AkashiRepair.js, tests/library/objects/Fleet.html, tests/library/objects/Fleet.js
The repair timer should behave as follows: a repair (re)starts when the
player modifies their fleet from the Organize screen, and the resultant
fleet has meets the correct conditions (Akashi flagship, not red/orange
HP, not in docks). Modifying the fleet in other ways - i.e. scrapping,
modernization, equipment change - will not affect the timer.
When the player visits the homeport and at least 20 minutes have passed
since the repair started, HP will be recovered and the timer resets. If
it has been less than 20 minutes, no action is taken.
The number of ships affected by the repair is based on the number of
Ship Repair Facilities equipped by Akashi at the time the repair is
applied.
(This is my first time contributing to a public repository, so hopefully I didn't make too much of a mess …
=> Fix #1378 Rewrite Akashi timer to match ingame behaviour

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/managers/QuestManager.js, src/library/modules/Service.js
This feature allows you to synchronize quests and progress between different computers.
You should enable account synchronization in your browser settings to use this feature.
Note: This feature also synchronizes the quests reset time to avoid a double reset.
Signed-off-by: Aleksei Mamlin <mamlinav@gmail.com>
=> Sync quests data on different machines via Chrome Storage

src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js
Changes:
- Fix GS rate for non-drum expeditions with unsparkled ship(s) (see #1951)
- Output GS rate of `"0%"` if expedition requirements are not met (previously was `"???"`)
- Colour GS rate text golden if overdrumming is active (previously would also turn gold when `sparkledCount` >= 4 for regular expeditions)
I am open to advice regarding the latter two changes. The way they behaved previously was bugging me, but I'm uncertain this is better, particularly the last change.
=> Improve expedition GS rate prediction

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/managers/QuestManager.js, src/library/modules/Service.js
Changes:
* Use 'assets/img/quests/sortie.jpg' as icon
* Use locale-based date and time in notification
* Add a setting for enabling data synchronization notification
* Define version of data structure in QuestManager
* Use data version instead of timestamp for checking new data
Related to #1959
=> Update data synchronization feature

src/library/objects/AkashiRepair.js, src/pages/devtools/themes/natsuiro/js/Shipbox.js, src/pages/devtools/themes/natsuiro/natsuiro.js
- Move repair time tooltip down so it doesn't overlap the Akashi repair timer on ship HP bars ([old](http://i.imgur.com/bdF2clk.png), [new](http://i.imgur.com/vfZB18Q.png))
- Persist Akashi Repair timer using localStorage
- Fix Akashi repair timer output if start time is unknown ([example](http://i.imgur.com/DwEvw4J.png))
=> Improve Akashi Repair timer display

src/data/settings.json, src/library/injections/dmm_takeover.js, src/library/managers/ConfigManager.js
* Fix background image size issue by dynamically setting window min-height (Close #1824)
* Also take top margin and zoom scale into account (Close #1989)
* Clean config attributes not used any more
* Also add a setting to customize CSS of DMM top page like panel and SRoom one
* But should keep this in mind: the CSS can be customized by injected content scripts is only applied to the top DMM site. The OSAPI gadget iframe (which game Flash Player inside) will not be affected directly. 
```
top dmm page (www.dmm.com)
|
\ -- `#game_frame` osapi gadget iframe (osapi.dmm.com)
|
\ -- `#externalswf` flash player embed (your server ip/kcs/mainD2.swf)
```
@KC3Kai/product the `min-height` of window is a simple calculation to avoid scroll bar appearing, please test this on your side to see if any …
=> Update CSS customizations of DMM site play mode

src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js
Kind of a reminder that the dropped ship is a ship you don't have and you *might* want to heart lock her.
Possible 'bug': If someone gets a new ship on a early node, and then get the same ship in a further node, it will get tagged as a 'new' ship. This is because ships are added to `KC3ShipManager` **after** returning to port.
=> Show green border around new ship drops

src/pages/strategy/tabs/ships/ships.css, src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
Saving length unfixed filters/sorters to URL hash seems troublesome, instead, store them into `localStorage` like other tabs do. 
* Settings saved to `localStorage`: filters (inc stypes), sorters (inc multi keys), special states of viewing (page no, equip mode)
* Add a button to remove settings from `localStorage` (that means reset all to defaults)
* Indicate sorted column head (not suit to show an order arrow because orders of columns are indeed different...😅)
=> SRoom Ship List supports settings saving

misc/uglify-harmony.patch
Latest UglifyJS harmony branch are released with uglify-es 3.x, which is broken for us now.
So use grunt-contrib-uglify compatible 2.x harmony patch instead.
=> Fix uglify-js harmony patch version

src/pages/strategy/tabs/ships/ships.css, src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
DONE
* Fixed scroll-able ship list table (might solve #2045)
* Duplicated ships filter (similar with #1880)
* Show small heart-lock indicator
* Adjust order of filter controls, put correspond group at proper place
* Fold / unfold filters, could make ship list larger (fold state will not be remembered)
* Add default sorter which in-game also uses, the order will be the same with in-game one when selected sorter are same values
* Update FAQ texts
Usage hint: for fixed scrollbar mode, once u resize your browser window/tab, manually click on `List Scrollbar Fixed` again to auto fit the height of ship list.
SS:
New filters order:
=> Ship list enhancements

src/library/managers/SortieManager.js, src/library/objects/Ship.js, src/pages/strategy/sortielogs.js
Allows the battle replay to show the boss bar:
* For regular world maps (including EO maps): only new runs will record boss bar info, old replays will not show.
* For event world maps: new runs ofc, if old maps stats data not lost, old replays will also show boss hp bar.
=> Battle replay bossbar

.jshintrc, src/pages/strategy/shipgrid.js, src/pages/strategy/strategy.html, src/pages/strategy/tabs/docking/docking.html, src/pages/strategy/tabs/docking/docking.js, src/pages/strategy/tabs/shipquests/shipquests.html, src/pages/strategy/tabs/shipquests/shipquests.js, src/pages/strategy/tabs/ships/ships.js
Just wanna reuse more codes for those `ship list` liked pages, current: `docking`, `shipquests`.
Should no feature changed. More similar pages will be easier to be created.
(will merge into `update-cumulative` branch, to test grunt package)
=> Refactoring ship list based pages

src/pages/strategy/tabs/expcalc/expcalc.js
Completely remove box of 155 ships after removing them from current goals.
Fixes ![image of bug](https://cdn.discordapp.com/attachments/205766705463427072/327853213070000128/unknown.png)
=> Fix removal of Lv. 155 ships of leveling tab

src/library/objects/Quest.js, src/pages/strategy/tabs/translations/translations.css, src/pages/strategy/tabs/translations/translations.js, src/pages/strategy/themes/dark.css
Allows addition of a TL for every tracking line, could be used for weekly 1, quarterly ranking and quarterly expedition.
```json
"214": {
"code": "Bw1",
"name": "Weekly Sorties",
"desc": "Sortie 36 times, reach 24 boss nodes, B-Rank+ 12 boss nodes, and obtain 6 S-Ranks.",
"memo": "\u203bOperation A-Go",
"unlock": [ 221 ],
"tracking": [ [0,36], [0,24], [0,12], [0,6] ],
"trackTypes": [ "Sorties {0}", "Reach bosses {0}", "B+ bosses {0}", "S-ranks {0}"]
},
...
"854": {
"code": "Bq2",
"name": "Quarterly Ranking Points",
"desc": "Sortie Fleet 1 to [W2-4], [W6-1] and [W6-3] and A-Rank+ the boss nodes of each. Sortie to [W6-4] and S-Rank the boss node.",
"memo": "\u203bBattle Results Extension Mission! \"Operation Z\", Preliminary Operation\n\u27a3Rewards 3 Mamiya, 4 Screws and 350 Ranking …
```
=> Add support for multi-tracking TL's

src/pages/strategy/sortielogs.js
Changing steganography.js's "t" (bits per pixel) breaks decoding of old images which might cause undesired effects on battle replayer.
=> Scale steganography image with large sortie data

src/library/objects/ShowcaseExporter.js, src/pages/strategy/tabs/showcase/showcase.html, src/pages/strategy/tabs/showcase/showcase.js
i guess i should ask someone to validate my engrish :rofl:
so it looks like so
first you either lock your ships in sortie or inside strategy room **Locking** page.
Then you click that checkbox above and have something like this
or in case of Light version this
Colors might be discussed but i rather leave them as is, since Tanaka already trolled us with this two:
=> Showcase update: event ship locks

src/pages/strategy/tabs/ships/ships.css, src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
Adds button to export to [kancepts](https://javran.github.io/kancepts/) (#2196) and [kanmusu list
](http://kancolle-calc.net/kanmusu_list.html)
Export to kancepts exports all locked ships.
Export to kanmusu list exports all currently visible (filtered) ships.
=> Add export to kancepts and kanmusu list buttons to ship list, adds #2196

src/pages/devtools/themes/natsuiro/js/Shipbox.js
Adds how much HP left till chuuha in HP tooltip;
Also, always show taiha/chuuha HP even when ship is already taiha/chuuha:
For terms.json:
```json
"PanelTaihaHpLeft" : "Taiha HP = {0}, {1} left",
"PanelTaihaHp" : "Taiha HP = {0}",
"PanelChuuhaHpLeft" : "Chuuha HP = {0}, {1} left",
"PanelChuuhaHp" : "Chuuha HP = {0}",
```
=> Add Chuuha HP left to hp hover, always show taiha/chuuha HP in tooltip.

src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js
When player has at least 1 mackerel: show mackerel counter
When player has 0 mackerel (eg, outside of events): show FCM counter
Also split up mamiya and irako counter in hover
=> Change FCM to fish counter during fish events + split mamiya & irako in tooltip.

src/library/injections/dmm_takeover.js, src/library/modules/Translation.js, src/pages/game/api.js, src/pages/game/dmm.js, src/pages/strategy/tabs/mstship/mstship.js, src/pages/strategy/tabs/quotes/quotes.js
Allows per line timing of subs. Also allows custom fadeout times for slow lines.
Example for Yamagumo:
```json
"Poke(2)": {"0,2300": "You can't do that~ That's delicate~ The depth charges, they're sensitive~"},
```
Example for quotes.json with one of the new quests; https://www.youtube.com/watch?v=VU8S80Bghqs
```json
"1187": {
"0":"Michishio: \"Why did they assign me to this fleet...?\"",
"3530": "Shigure: \"Oh, Michishio. Nice to see you.\"",
"7500": "Michishio: \"Shigure?! What are you doing here? Don't tell me we're in the same unit!\"",
"15720": "Shigure: \"Looks like it... Force C of the First Striking Force...\"",
"22900": "Michishio: \"What's wrong, Shigure? You don't look so good. Maybe you should lie down for a bit.\"",
"30540": "Shigure: \"It's okay, I'm fine. It's because of …
```
=> Add ability to time subtitles

.jshintrc, src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/Network.js, src/library/modules/TsunDBSubmission.js, src/library/objects/Fleet.js, src/library/objects/Ship.js, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/plain.html, src/pages/devtools/themes/plain/plain.js
* Including PRs:
* https://github.com/Tsubakura/KC3Kai/pull/1
* https://github.com/Tsubakura/KC3Kai/pull/2
* Replace n/a KC3 data submission setting with new one
To answer sin_sin's questions:
- Preferably, I dont want to use stype() at all, I just need to know the ship type id.
- Wouldnt it take more time to send everything? Is it also necessary? The data already includes anything that is sortie related, excluding LBAS setups.
I prefer that those properties in data are added back in during the initialization, it serves as a summary as to what data is sent over to the server.
=> Routing database submission

src/library/managers/SortieManager.js, src/library/modules/BattlePrediction.js, src/library/modules/BattlePrediction/Fleets.js, src/library/modules/BattlePrediction/phases/Util.js, src/pages/strategy/tabs/shipdrop/shipdrop.js, src/pages/strategy/tabs/ships/ships.js, tests/library/modules/BattlePrediction.js, tests/library/modules/BattlePrediction/Fleets.js, tests/library/modules/BattlePrediction/phases/Hougeki.js, tests/library/modules/BattlePrediction/phases/Raigeki.js, tests/library/modules/BattlePrediction/phases/Util.js, tests/library/modules/BattlePrediction/phases/Yasen.js, tests/library/modules/BattlePrediction/values/Target.js
(Temporarily?) disabled the old test/library/modules/BattlePrediction.js
since it was using outdated api data.
=> Make unit tests pass

src/library/modules/BattlePrediction/engagement/EngagementTypes.js, src/library/modules/BattlePrediction/phases/Hougeki.js
CF hougeki phase also now respects both fleets in its attacker and
defender indices (i.e. escort fleet is now 6-11)
=> Fix CF day shelling

src/library/modules/BattlePrediction.js, src/library/modules/BattlePrediction/Fleets.js, src/library/objects/Node.js, tests/library/modules/BattlePrediction/Fleets.js
=> Improve night-to-day node support

src/library/objects/Node.js
LBAS indicator was incorrectly visible on night-battle nodes; both in the Strategy Room and on the devtools panel
Fixes: #2364
=> Fix LBAS indicator visble on NB nodes

src/library/objects/Node.js, src/pages/strategy/sortielogs.js
Shift to 0-based arrays in the kcsapi meant that damage to the first
land base was being ignored.
=> Fix LBAS raid damage calculation

src/pages/devtools/themes/natsuiro/natsuiro.js
Example terms.json:
`	"ConsumablesFCoinBoxes" : "{0} × 200 box = {1}\n{2} × 400 box = {3}\n{4} × 700 box = {5}\nIn boxes = {6}\nTotal = {7}",
`
=> Add fcoin boxes in fcoin tooltip in panel

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/Meta.js, src/pages/devtools/themes/natsuiro/js/Shipbox.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Format ship left exp, resources and furniture coins.
Result depends on user's locale;
=> Format panel ship left exp, resources

src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/devtools/themes/plain/plain.js
Update custom css in real-time for panel without closing and reopening panel.
[Example gfycat](https://gfycat.com/ElaborateNiftyIndianabat) 
Can change TL for hover after this is merged to reflect changes;
=> Live panel css updates

package.json, src/data/developers.json, src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/TsunDBSubmission.js, src/library/objects/Node.js, src/library/objects/Ship.js, src/library/objects/ShowcaseExporter.js, src/manifest.json, src/pages/devtools/themes/natsuiro/js/Shipbox.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/strategy/sortielogs.js, src/pages/strategy/tabs/aircraft/aircraft.html, src/pages/strategy/tabs/aircraft/aircraft.js, src/pages/strategy/tabs/encounters/encounters.js, src/pages/strategy/tabs/event/event.css, src/pages/strategy/tabs/gears/gears.js, update
* Will now switch to vertical damage summary when applicable for the panel support tooltip
* Show 3 more items on the panel (action reports, gun and aviation parts)
* Update TsunDB submission domain, and traffic now via `HTTPS`
* Show proper equipment type (icon) names at Strategy Room Equipment, Aircraft pages and exported Showcase image
* Other minor fixes
* `en` quotes
* `en` terms
* `fr` terms
* `id` terms
* `jp` quotes
* `jp` terms
* `ru` terms
* `scn` terms
* `tcn` quests
* `tcn` terms
* `th` battle
* `th` terms
=> Release 32.3.1

src/pages/strategy/tabs/ships/ships.css, src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/tabs/ships/ships.js, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
Strategy room's ship list now has the feature to filter by ship level on minimum and maximum limits.
1) Added "Start Level" and "End Level" input fields to the right of the existing "Show by Name" input field.
2) "Start Level" input field will dictate the minimum level that a ship must be in order to display in the list. (Level inclusive, so the list will include ships this level and higher.)
3) "End Level" input field will dictate the maximum level that a ship must be in order to display in the list.
(Level inclusive, so the list will include ships this level and lower.)
4) Both fields do not need to be specified - if both are specified then both filters will be applied, if one is specified then only one filter will be applied.
5) If the start level is greater than the end level, then an …
=> Added ship level filter to strategy room ship list

src/pages/strategy/sortielogs.js
Saw that we were adding lbas AP into encounters so decided to add it to airraid tooltip as well
Recons do take part in LB airraids **https://cdn.discordapp.com/attachments/345068113978458113/421001464798773258/2018-3-7T20.48.41.png**
Sorry for making the tooltip longer
=> Added enemy air power (including recons) for LB airraid tooltip

src/library/managers/GearManager.js, src/library/objects/Ship.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js
Split enemies into currently known installation types and assign bonus based on type
1. normal enemy
2. Soft-skinned installation
3. Pillbox
4. Isolated Island Princess
5. Harbour Summer Princess Damaged
6. Supply Depot Princess
7. PT Imp (not included with anti-installation modifiers)
~~Add bonus for Northernmost Landing Princess~~ (Should be the same as normal ritou anyway)
Some of these bonus interactions (like average improvement levels) are speculative, also, lacking info on certain equipment like 11th Tank Regiment.
Will probably be used to sim damage for future abnormal damage checker
=>  Add anti-installation (and imps) additive/multiplicative bonus calculation

package.json, src/library/managers/ShipManager.js, src/library/modules/Kcsapi.js, src/library/objects/Node.js, src/library/objects/Ship.js, src/manifest.json, src/pages/strategy/sortielogs.js, src/pages/strategy/tabs/badge/badge.js, src/pages/strategy/tabs/pvp/pvp.js, update
* Hovering over the Sortie ID in the Sortie History will now show you how many resources were used in that sortie
* **NOTE:** LBAS consumption and Akashi repairs are not counted
* Resource amounts are not updated real time but will update when you push the resupply button
* Resources gained from the sortie is counted towards the final resource total
* Old sortie records should work just fine however PVP records will only start showing resources used after this update
* Minor back-end changes
=> Release 32.6.0

src/library/objects/LandBase.js, src/pages/devtools/themes/natsuiro/natsuiro.js
Added preliminary calculation for land base defense in air raid from https://kancolle.wikia.com/wiki/Land_Base_Aerial_Support#Enemy_Raid_2
Added mouseover tooltip to display slot shotdown numbers when land base is set to defense
AS is used rather than AS+ since most event situation is either AS or AP for perfect defense
"LandBaseDefenseShotdown" : "Shotdown under AS\nSlot 1: {0}\nSlot 2: {1}\nSlot 3: {2}\nSlot 4: {3}",
=> Air raid defense shotdown prelim calculation

package.json, src/data/developers.json, src/library/modules/BattlePrediction.js, src/library/modules/BattlePrediction/BattlePrediction.js, src/library/objects/Node.js, src/manifest.json, src/pages/devtools/themes/natsuiro/natsuiro.js, update
* Please be advised that KanColle will be Shut Down for 2 Days for the KanColle Phase 2 (HTML5) [Block-1] Maintenance & Updates from Wednesday, August 15th from 11:55 AM JST and is expected to end on Friday, August 17th at 18:00 JST
* KC3改 will most likely be broken after this update, however, we will work as quickly as we can to get it working again after the maintenance, we request you have patience
* Also don't forget to send your long expeditions before the start of the Maintenance
* Mousing over the battle prediction rank result on the panel will now show combined damage gauges
* `de` items
* `de` quests
* `de` terms
* `en` quests
* `en` terms
* `jp` quests
* `jp` quotes
* `jp` terms
* `scn` terms
=> Release 32.8.0

src/library/modules/PoiDBSubmission.js
Schema was [updated](https://github.com/poooi/poi-server/blob/97fe091b753d818ac5af01d49fb7ae89598a0f89/models/report/drop-ship.es#L17) to support `api_get_base_exp`.
=> Add baseExp for PoiDB

src/library/objects/Gear.js, src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.html, src/pages/devtools/themes/natsuiro/natsuiro.js, src/pages/strategy/tabs/aircraft/aircraft.css, src/pages/strategy/tabs/aircraft/aircraft.html, src/pages/strategy/tabs/compare/compare.css, src/pages/strategy/tabs/compare/compare.html, src/pages/strategy/tabs/fleet/fleet.html, src/pages/strategy/tabs/gears/gears.css, src/pages/strategy/tabs/gears/gears.html, src/pages/strategy/tabs/mstgear/mstgear.css, src/pages/strategy/tabs/mstgear/mstgear.js, src/pages/strategy/tabs/mstship/mstship.css, src/pages/strategy/tabs/mstship/mstship.html, src/pages/strategy/tabs/mstship/mstship.js, src/pages/strategy/tabs/ships/ships.html, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
* Replaced stats icons of almost all pages with phase 2 version
* Ship List grid caption not replaced (perhaps there are still some pages forgotten?)
* Icons originally crafted by us not replaced (who make some new?)
* New 'HD' icons are not only larger size, but also different aspect ratio
* Have to adjust their css sizes by hands... so they look not so good after zoomed out, maybe not suit for current 'compact' theme. 🤔 
Plz try and check if they are good to go, imo do not like them anyway 😂
=> Update stats icons of ship & equipment

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/managers/SortieManager.js, src/library/modules/TsunDBSubmission.js, src/pages/strategy/strategy.html, src/pages/strategy/tabs/gunfits/gunfits.css, src/pages/strategy/tabs/gunfits/gunfits.html, src/pages/strategy/tabs/gunfits/gunfits.js, src/pages/strategy/themes/dark.css, src/pages/strategy/themes/legacy.css
Automated submission of samples for purpose of (gun)fit verification.
Works by having some page in strategy room where testers can see which tests they can do, and choose one to do. This will make anyone able to do help out with these tests since barrier of entry previously was way higher (setting up logbook, calculating yourself etc). Moving the setup & calculation part away might make it more appealing to some. 
Tab:
Shows whenever or not the user has the required ship/level/equipment and disable the ones that are impossible to test currently.
When the tester has the ship(s) set up, it'll color yellow/green depending on if correct morale has been reached.
=> TsunDB gunfit tests

src/library/objects/Node.js, src/pages/devtools/themes/natsuiro/js/Shipbox.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js
Add a purple background to shipboxes involved in special attacks (Nagato Cutin/Nelson Touch)
Highlight node letters where special attack has activated
Node letter highlight is only added on battle results
EDIT: realized that the purple bg blocks out the red taiha bg and could be potentially dangerous for players in the below case
EDIT2: fixed
Day battle example
Night battle
Resolves https://github.com/KC3Kai/KC3Kai/issues/2733
=> Add indicator for one-time sortie attacks

src/library/modules/Kcsapi.js, src/library/modules/TsunDBSubmission.js
Uses KC3Network listener because Kcsapi.js will have handled the modernization by the time the (async) DB submittor gets it (can't get lvl/master id of consumed ships / mod difference).
=> Add DE modding submissions for TsunDB

src/library/modules/Meta.js, src/pages/strategy/tabs/mstship/mstship.css, src/pages/strategy/tabs/mstship/mstship.html, src/pages/strategy/tabs/mstship/mstship.js, src/pages/strategy/themes/dark.css
Filter equipment bonuses that ship is valid for and display it in mstship. For simplicity, only single bonus from gear is displayed.
May need to add new terms
For white theme
For dark theme
Thanks to @DynamicSTOP
=> Display ship bonuses with equipment in ship library

src/data/settings.json, src/library/managers/ConfigManager.js, src/pages/devtools/themes/natsuiro/natsuiro.css, src/pages/devtools/themes/natsuiro/natsuiro.js
Show green name for friends in PvP opponents list. Toggle friend/normal by clicking on name, or by adding manual in line separated setting.
Might also add name coloring to PvPFleet or user ID support in case there are multiple people on your server with same name as a friend.
=> PvP opponents friend list

src/pages/strategy/tabs/overlodger/overlodger.js
The kc3 ledger suddenly stops working if your resource history is extensive enough. This is because current behavior of using apply with newTotalBuffer calls unshift with as many args as there are items in your resource history. The javascript engine does not like this when that number starts reaching hundreds of thousands.
To fix, we slice newTotalBuffer and prepend it in batches.
=> Fix ledger not working with very large history

src/library/modules/TsunDBSubmission.js
For [`api_cell_flavor`](https://github.com/andanteyk/ElectronicObserver/blob/develop/ElectronicObserver/Other/Information/apilist.txt#L1563) in `api_req_map/next`, should be some event-related text that popup on empty nodes.
=> Add node flavor text in TsunDB

src/library/managers/ConfigManager.js, src/pages/devtools/themes/moonlight/moonlight.css, src/pages/devtools/themes/moonlight/moonlight.html, src/pages/devtools/themes/moonlight/moonlight.js
Adjusts the display of a few elements within the moonlight theme so that a larger number of quests can be displayed. Users must press the appropriate button in order to activate the large quest display view mode.
The square, wide and tall layouts are affected. The compact layout does not require changes at this time.
[imgur screenshots](https://imgur.com/a/pRskbki)
=> moonlight - ad hoc support for more listed quests

src/library/modules/Network.js
Currently, SE mode will cause the blocker to never trigger if the user reduces the ingame SE level to 0. This PR adds a check to the network handler which verifies the ingame volume level via the dmm cookie kcs_options=>vol_se, and if it is set to 0, allows the blocker to operate as though in Network mode.
=> blocker SE mode falls back to Network when muted

src/library/modules/PoiDBSubmission.js
Recently we rethink about poi db server design and we introduced something new.
This PR updates the submission API:
- update the api server address and scheme
- add kc3kai version info for data filtering based on kc3kai version
- sending pure json payload to the server, and adds `X-Reporter` to request header as a alternative for user-agent (i'm considering removing origin in payload, but there's no conclusion yet)
- remove knwon recipe check because the server can handle duplicating recipes now
=> feat: update poi db submission api

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/Kcsapi.js
When user enters map selection menu, if user-chosen fleet has empty equip slots, user will be given a warning on which ships have empty equip slots.
At event map pre-sortie check, if user has untagged ships, user will be given a warning on which ships do not have tags.
Non-heartlocked ships will be ignored.
This is inspired by poi feature where user is given warning pre-sortie for ships with no lock during event.
=> Add pre-sortie warning for ships with empty equip slots or shiplock

src/pages/strategy/tabs/eventstats/eventstats.css, src/pages/strategy/tabs/eventstats/eventstats.html, src/pages/strategy/tabs/eventstats/eventstats.js
Display ships from the recorded sunk entries and capture damecon/damegami usage
Damage control usage is not accurate because flagship advance is not recorded
Also assume that player will not sink a ship that has already used damage control
=> Add ship sunk and damage control statistics to eventstats

src/library/modules/TsunDBSubmission.js
1. Added HP after opening/closing torpedo for Abyssal attackers. Opening torpedo data from Abyssal attackers are now submitted.
2. Added HP after the combat phase of every 'attack' (e.g. if 'attack' is the first attack of single vs single combat, then the combat phase is 'hougeki1') for the escort ships in NagaMutsu/Colorado Touch. These HPs are used to filter out potentially invalid spattack submissions.
=> Refinements to the TsunDB submitter

src/data/settings.json, src/library/managers/ConfigManager.js, src/library/modules/Service.js
Hi, I've been using Pushbullet and Parsec for expeditions for a month.
But there was a problem that bothered me.
It also will send other notifications like construction, repair, etc.
I want the expedition notification only.
So I've added an option, as well as translations for EN, JP, and CN.
https://github.com/Sean2525/KC3Kai/commit/5a3b72ed5e6be1b1ac25dc3f290234f28c08f1c5
https://github.com/Sean2525/kc3-translations/commit/897087137869314bcb881d2f5e753c8e8d10ef9e
The notifId can be used to check if it is an expedition.
https://github.com/KC3Kai/KC3Kai/blob/408ca39eb817dcae852a8676069043e061b737ab/src/library/objects/Timer.js#L174-L179
After I tried it for a day, it works well.
Could you help review it? 
Thanks.
=> Add expedition only config for pushalert
