src/pages/game/screenshot.js

Changed from
`1431161311_81.jpg`
to
`KanColle_2015-04-09_15-53-21.jpg`

Fix #52 Human-readable Screenshot Filename

---

src/pages/strategy/css/lscs.css
src/pages/strategy/html/lscs.html
src/pages/strategy/tabs/TabLscs.js

Added DevMat count
Though the CSS might need some tweaks (I'm not quite good at CSS stuffs lol)
using hardcoded values for testing
using real/original values

fix #92 devmat on LSC history

---

src/pages/panel/classes/Dashboard.js
src/pages/panel/classes/Reactor.js
src/pages/strategy/tabs/TabE_spring2015.js

* Allows quick ship checking for ship swapping purpose.
* Reduces conditional check and transfer new item logging from Show Craft Box to Reactor/CreateItem

[Fix #89] [Fix #3] Fix Certain Panel Problem

---

src/library/classes/Config.js
src/pages/panel/panel.js
src/pages/settings/settings.html
src/pages/settings/settings.js

[Fix #99] Panel Background Alignment Settings

---

src/pages/panel/classes/Listener.js

[Fix #98] Quest Translations are not dismissed

---

src/pages/panel/classes/Dashboard.js
src/pages/panel/classes/Listener.js

[Fix #116] Compass Result of 1-6 Resource Node (Boss Node) showing incorrectly

---

src/pages/panel/classes/Dashboard.js
src/pages/panel/panel.css

Previously, when showing "Unknown Enemy" or "Battle Avoided" result, the text was aligned to the left. Now I put it to the center. Just a minor bug.

Fix alignment of "Unknown Enemy" result and "Battle Avoided" result.

---

src/library/managers/TimerManager.js
src/library/modules/Dashboard.js
src/library/modules/Panel.js
src/library/objects/Timer.js
src/pages/devtools/themes/default/default.css
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

Solved #157
@dragonjet Here is the Normal Mode for Vertical Layout. Just tell me if you want any amendment. :smile:

[Feature #157] [v10] Dashboard: Vertical (Normal Mode)

---

src/library/objects/Node.js

Fixed #192
Now it works. I can even show the type of plane that has Contact xD

[Fix #192] Contact on KC3 battle mode not work properly

---

src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

[Fix #207] Vertical Orientation PvP Faces

---

src/pages/strategy/tabs/ships/ships.css
src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js

and some tweaks for ship list filters tabs CSS

new filters for Ship List: Remodel & Modernization

---

src/data/translations/en/settings.json
src/library/managers/ConfigManager.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

I added 2 buttons on the right side of the Dashboard (only Vertical Layout) to select the size for it.
__Small (300px)__
__Big (420px)__
We also can change it in Settings Page.

[Feature] Size option for Vertical Layout

---

src/pages/strategy/tabs/gears/gears.css
src/pages/strategy/tabs/gears/gears.html
src/pages/strategy/tabs/gears/gears.js

Equipment list

---

src/pages/devtools/themes/default/vertical/vertical.css

[Fix #206] Changed color of modernization quest box

---

src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js

[Fix #234] Maelstrom resource type and count shown are wrong

---

src/data/translations/jp/settings.json

From #229. Alert section done. Trying to do the later paths if I could wake up early today. :v

[Translation: Japanese] [Settings] edited (translated) on 警報 (alert) section.

---

src/data/translations/jp/settings.json

From #229. This work should be finished now. All sections are translated.

[Translation: Japanese] [Settings] Finished.

---

src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.js

[Fix #248] Night Battle Indicator on Practice

---

src/library/modules/Meta.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

[Feature] Enemy formation for vertical layout

---

src/data/translations/en/developers.json

copy paste too much and forgot to delete the comma xD

minor tweak for about developer on english

---

src/data/translations/jp/developers.json

same case, forgot to remove the comma xD.
i dont know how to merge this to previous pull :cry:

Update developers.json for jp settings

---

src/data/translations/en/developers.json
src/data/translations/tcn/developers.json
src/data/translations/tcn/quests.json
src/data/translations/tcn/terms.json

Chinese translation v.1.1

---

src/data/translations/jp/settings.json

Simplified Chinese choice added and "alert_custom" id naming fixed (no more URL).

[Translation: Japanese] [Settings] Adding SCN and minor fixing.

---

src/data/translations/jp/terms.json

New variable; "SettingsTitle", "LearnMore" and "Saved".

[Translation: Japanese] [Terms] Adding new variables.

---

src/data/translations/jp/developers.json

All of these devs should be translated...

[Translation: Japanese] [Developers] Finished.

---

src/pages/strategy/strategy.html

For the sage of upcoming Summer 2015 event. We should not recommend people to do LSC before the event started. lel

Remove #JustDoIt on the LSC tab.

---

src/pages/strategy/tabs/gears/gears.css
src/pages/strategy/tabs/gears/gears.js

changed the font size to 14px and made it bold type
https://github.com/dragonjet/KC3Kai/issues/275

Improve readability for equipment totals

---

src/pages/strategy/tabs/builds/builds.css
src/pages/strategy/tabs/builds/builds.html
src/pages/strategy/tabs/lscs/lscs.css
src/pages/strategy/tabs/lscs/lscs.html

Preview shown on construction page.

Added key legends to construction and lsc tabs.

---

src/data/translations/jp/settings.json

From #290, no need in "non-text" variable contents.

[Translation: Japanese] [Settings] Following enhancement in #290.

---

src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

https://github.com/dragonjet/KC3Kai/issues/286

Apply for vertical mode

---

src/library/helpers/ExpeditionHelper.js
src/pages/devtools/themes/default/default.html
src/pages/devtools/themes/default/horizontal/horizontal.html
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

A quick fix to make it work with new API, keep in mind that this messes up the current layout a little bit.

ExpeditionHelper quick fix

---

src/data/translations/jp/quests.json

[Translation: Japanese] [Quests] Completed.

---

src/data/translations/jp/developers.json

Welcome new translators, Admin Mikado of KC wikia (lel) and Arkayda.

[Translation: Japanese] [Developers] DE and FR added.

---

src/data/translations/id/quests.json
src/pages/strategy/tabs/gears/gears.js

my bad the equipment strategy was like this
it supposed to be like this
and made some changes to quest translation

Fixed some stuff

---

src/data/translations/scn/quests.json

zhCN update (all weekly & monthly quests)

---

src/data/translations/jp/README.md

[Translation: Japanese] [README] JP translation for the reference.

---

src/library/managers/QuestManager.js
src/library/managers/SortieManager.js
src/library/objects/Node.js

[Fix #343] Weekly Sortie 1 Stops Counting at 35/36

---

src/data/translations/jp/terms.json

On `MenuAboutDesc` and `AboutTitle`, 改 lost on somewhere when I was so sleepy and forgot to type it... :<

[Translation: Japanese] [Terms] [Minor] forgotten 改.

---

src/library/managers/SortieManager.js

[Fix #382] Air battle encounter doesn't show up in battle mode's panel

---

src/library/objects/Node.js

[Feature] Tracking abyssal Carrier, Transport Ship and Submarine hunt quests

---

src/library/objects/Node.js

[Fix #396] No image for icon box node

---

src/data/translations/en/ships.json

Wonder... I also have no any ideas why she isn't there yet (#402). lel

[English] [Ships] Adding Prinz Eugen.

---

src/data/translations/scn/quests.json
src/library/modules/Translation.js

the extend method for the new KC3Translation.getJSON() is not perfect since it use non-recursive extending. this will fix that
now non-text content can be safely removed from all translation files except `terms.json`

KC3Translation.getJSON - recursive extend

---

src/pages/devtools/themes/default/horizontal/horizontal.css
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.js

[Feature] Tooltip and hover effect for gears (Tooltip Series part 1)

---

src/library/managers/SortieManager.js
src/library/modules/Kcsapi.js
src/library/objects/Node.js
src/pages/devtools/themes/default/horizontal/horizontal.css
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.js

* triggering ThemeXXXDefault.HQ basically resets the XP gain counter and
meter (calling this first then battleResult is the correct one, and actually there's no need to call HQ, since it will be automatically called whenever HQ level up)
* add animation for HQ Exp animation (it's ok for this lol)
* some sourcecode tidy up (easier with switch case ofc :P)

HQ Bar on Sortie not Update Fix

---

src/data/developers.json
src/data/translations/en/quests.json

Add full quest translation + add new Vietnamese translator

[Translation] Full quest translation (Vietnamese)

---

src/data/translations/en/quests.json
src/data/translations/vi/quests.json

Fix #435
Reversed quest translation of English
Copied translation to Vietnamese

[Fix #435] Quest Translation

---

src/library/objects/Ship.js
src/pages/devtools/themes/default/horizontal/horizontal.css
src/pages/devtools/themes/default/horizontal/horizontal.html
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

[Feature] Show Plane Capacity in Normal Mode

---

src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

Add Screenshot button on Battle Mode for vertical

---

src/data/translations/jp/terms.json

Contain `AboutReporters`, `AboutReporter`, `SettingsDropFaces`, `SettingsYasenTroll` and `SettingsHQDelta`.

[Translation: Japanese] [Terms] Adding new variables (4).

---

src/pages/devtools/themes/default/vertical/vertical.css
src/pages/devtools/themes/default/vertical/vertical.html
src/pages/devtools/themes/default/vertical/vertical.js

[Fixed #452] Battle Spoiler/Prediction is wrong for vertical orientation

---

src/data/settings.json
src/data/translations/en/terms.json
src/library/managers/ConfigManager.js
src/library/managers/SortieManager.js
src/library/objects/Player.js
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js
src/pages/game/api.js

Quick Fix and Feat

---

src/pages/devtools/themes/default/vertical/vertical.css

[Fix #459] Battle Info glitch(?)

---

src/library/modules/Network.js

I don't have the issue in #465 but still made an attempt to fix it. Not sure if the change really fixes the issue or not. @McDohl Could you try my branch first?

[Fix #465] Ask Quest Page 

---

src/data/translations/jp/terms.json

`UntranslatedQuest` and `PanelWaitActions` (also minor fixing on `SettingsPanelRequirement`).

[Translation: Japanese] [Terms] Adding new variables (6).

---

src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js

[Fix #476] PvP only shows first opponent ship

---

src/library/objects/Node.js

Fix #482
Since it's just purely copy/paste, it is an untested fix but it should work :sweat_smile:

[Fix #482] battle prediction not updated for night battle 

---

src/data/translations/jp/terms.json

'SettingsDMMForceCookies' added for new measure in DMM's Cookies.

[Translation: Japanese] [Terms] Adding new variables (7).

---

src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js
src/pages/strategy/tabs/maps/maps.css

https://github.com/dragonjet/KC3Kai/issues/489

Add Tooltips for Formation

---

src/data/translations/jp/terms.json

* `HQExpAbbrev1...3` for improved HQ's exp displaying.
* `SettingsBattleStamp`, `PredictionStampSortie` and `PredictionStampPvP` for newly prediction stamping function.

[Translation: Japanese] [Terms] Adding new variables (8 and 9).

---

src/data/translations/scn/terms.json
src/pages/popup/popup.js

details on fix for #510
added a check for chrome.cookies for both `Play via API Link` and `Refresh API Link` function

zhCN update and fix for #510

---

src/data/translations/vi/terms.json

[Translation] Update new terms for Vietnamese

---

src/data/translations/jp/terms.json

This time `APIWaitToggle` for the sage of API panel loading, right?

[Translation: Japanese] [Terms] Adding new variables (10).

---

src/library/modules/Kcsapi.js
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js

resolved #492
show Penguin with "Equipment crafting failed"

[Feature #492] Clear new equipment preview when development is unsuccessful

---

src/library/managers/SortieManager.js
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js

[Fix #529] [Bug] Night Battle: Just Another Bug

---

src/data/translations/vi/ranks.json
src/pages/devtools/themes/natsuiro/natsuiro.js

@dragonjet is it still possible to include this commit in v15?

[Translation] Change HQ rank translation in Vietnamese

---

src/data/translations/vi/quests.json
src/data/translations/vi/terms.json

update terms.json and quests.son

[Translation] Add new terms and update quest translation in Vietnamese

---

src/data/translations/id/terms.json

Sorry i'm late
Should've translated this before the release

[Translation:Id] Translated Battle and fix some translation

---

src/data/translations/jp/terms.json

For Natsuiro theme updating...

[Translation: Japanese] [Terms] Adding new variables (11).

---

src/data/translations/en/ships.json

Added Mizuho and Hayasui.
Also reorganized all auxiliary ships.
P.S. Sorry for the deleted fork. I'm not all all that familiar with github yet.

Adding some Kanmusu names in English version

---

src/data/translations/en/quests.json

Added the initial quest.
More will come along the way, but we'll start with this one for now.
EDIT: Derp, forgot that this is json record file instead of javascript source code, removed the comments.

Addition of Quest 280

---

src/library/objects/Node.js

Fix #596
@ethrundr After this gets emerged, could you test it on yasen node for me?

[Fix #596] Uncaught TypeError: Cannot read property '0' of undefined

---

src/library/objects/Node.js

I recommend to merge this and #602 at the same time :grin:

Integrate DamageAnalysis with current code

---

src/data/translations/en/quests.json

Added event quests up until SN05.

Added Event Quest Translations

---

src/data/translations/en/quests.json

Added all event quests except SN08

Updated Event Quest Translations

---

src/data/translations/en/quests.json

Added Murata's plane conversion quest and updated existing plane conversion quests. This should be all the event quests under the bag.
And no, I'm not going to put trackers or anything.

Updated Plane Conversion Translations

---

src/data/translations/jp/terms.json

This Summer 2015 Event was made me out of my duties for a long week...

[Translation: Japanese] [Terms] Adding new variables (12).

---

src/library/objects/Timer.js

I think "shipgirl" is more appropriate (and more charming) than "face".

[Timer] Be changing "Face" to "Shipgirl".

---

src/pages/strategy/tabs/ships/ships.css
src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js

[Feature #654] Add Night battle attack power column in Ship List in Strategy Room

---

src/data/translations/jp/terms.json

* KIDS CHOICE -> ワロタ
* HELL AF ->　やべー
* GET REKT SON -> 無理だ

[Translation: Japanese] [Terms] Adding new variables (13).

---

src/data/translations/jp/terms.json

Following the 19th August reworking.

[Translation: Japanese] [Terms] Adding new variables (14).

---

src/data/translations/jp/terms.json

[Translation: Japanese] [Terms] Adding new variables (15).

---

src/data/translations/jp/terms.json

Following ver. 18.2, `SettingsMoraleNotif` and `SettingsMoraleValue`.

[Translation: Japanese] [Terms] Adding new variables (15)

---

src/data/translations/en/terms.json
src/pages/strategy/tabs/event/event.css
src/pages/strategy/tabs/event/event.html
src/pages/strategy/tabs/event/event.js

- removing some unused proposed terms (yes, those strange colored stamp
lol)
- i haven't cosplayed yesterday. i need to met with a trap cosplayer though
- i won't say it's closes/finishes for now, just testing it :D

[Attempts #703] +

---

src/library/modules/Kcsapi.js

I hope I didn't get any off-by-one errors with the indices; I checked PlayerManager.js but I'm not entirely sure.

update display when bucket used on docked ship

---

src/library/modules/Kcsapi.js

I forgot to add the triggers for stuff last time.

add triggers for bucket-related events

---

src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/strategy/tabs/event/event.js
src/pages/strategy/tabs/maps/maps.js

https://github.com/dragonjet/KC3Kai/issues/739

Enhancement

---

src/library/modules/Kcsapi.js

another bucket fix; updates repair timer

---

src/library/managers/QuestManager.js
src/library/modules/Kcsapi.js

DON'T PULL THIS YET.  I haven't worked out how to fix it so that all 7 victories are in the same day but the quest only comes around once per month.

Quest tracking stuff for C8: Elite Fleet Practice

---

src/library/managers/QuestManager.js
src/library/modules/Kcsapi.js

Revert "Quest tracking stuff for C8: Elite Fleet Practice"

---

src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

and it's travis-kun is happy...

branch mess up

---

src/pages/game/api.js

FIX: Turn off quest translation no longer disable quest tracking now

---

src/data/developers.json

Add SerialConvort to testers

---

src/pages/strategy/tabs/wikia/wikia.js

Feature requested in #754.
You may find the DeckBuilder link in the console when you open Fleet->Export tab in Strategy Room.

Alpha build for DeckBuilder export feature(http://www.kancolle-calc.net/)

---

src/pages/game/web.html

Fixed StartGameText

---

src/library/objects/Quest.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.js

re: #298 
I couldn't figure out a good way to highlight the quests, so instead I'm putting a check mark in the colored box.

add checkmark to quest_color when quest completed

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/DBSubmission.js
src/library/modules/Network.js
src/library/objects/Request.js
src/pages/devtools/themes/natsuiro/natsuiro.html

Feature requested in #690 
You may obtain a access key at http://kancolle-db.net/login.php ( A twitter account is needed ) . Navigate to the setting page, enable the feature, paste the key and you're done.
You may check the collected data  at the above page.

Kancolle db submission

---

.travis.yml
src/library/modules/Translation.js
src/pages/game/api.html
src/pages/game/api.js
src/pages/game/web.html
src/pages/game/web.js

Don't merge yet until reviewed

Game page translations

---

src/library/managers/PlayerManager.js
src/pages/strategy/strategy.html
src/pages/strategy/tabs/docking/.dir-locals.el
src/pages/strategy/tabs/docking/docking.css
src/pages/strategy/tabs/docking/docking.html
src/pages/strategy/tabs/docking/docking.js

Modified from ship list, shows non-full HP ships with docking time / facility repair time (Akashi time)
The screenshot should be straightforward:

Strategy room: ship docking time

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/Network.js
src/library/modules/PoiDBSubmission.js
src/pages/devtools/themes/natsuiro/natsuiro.html

poi-statistics db submission

---

.gitmodules
src/pages/game/api.css
src/pages/game/api.js

including master commit though... the API blahblahblah that should be generick'd maybe....

Submodule Pointer Alter

---

src/library/helpers/ExpeditionHelper.js
src/library/objects/Fleet.js
src/library/objects/Ship.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

Expedition tab on natsuiro theme, most of the work is done by @nekoworkshop 
This feature is still under development, but for now I think it's good enough merging into master branch.

New feature: expedition tab

---

src/assets/js/global.js
src/library/modules/Kcsapi.js
src/library/modules/Network.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

See checked item in #978 for progress.
Implemented:
* remember user's last selection for each fleet
* colorize expeditions by availablity (feel free to edit CSS colors because I'm not good at this)
* under some conditions expedtion tab will be activated automatically:
* if there are fleets available for expeditions, switching to expedition selection screen will activate expedition tab
* after sending a fleet to expedition, if there are still fleets available, that fleet will be selected automatically

Expedition tab

---

src/pages/devtools/themes/natsuiro/natsuiro.html

Meh, yah, changed natsuiro this time. kek.

Another pull req for translations

---

src/pages/devtools/themes/natsuiro/natsuiro.html

so I leave another push here.
Also be on in gitter DJ ;)

meh, too early, was changing much.

---

src/pages/popup/popup.js

#1017 possible solution but makes some more changes than necessary.  I think the new code might be slightly more correct in terms of leap second handling, but then again I don't think anyone cares about leap seconds.

patch #1017: negative quest timer

---

src/pages/devtools/themes/natsuiro/natsuiro.js

* remove old code
* skip checking 2nd fleet if it's combined.

expedTab update

---

src/pages/strategy/tabs/mstship/mstship.js

* sort hourlies
* add `:` as separator

Fix mstship hourlies

---

src/library/modules/Kcsapi.js

Hopefully this fixes Bw8 tracking ( #541 ). I've completed my Bw8 so I might need verification on this @KC3Kai/testers

fix quest Bw8 tracking (4-4)

---

src/library/modules/Kcsapi.js

I haven't seen any data sample so this patch is just guessing. (I'm 90% confident)
need volunteers on E-3 (I haven't got there yet).

Handle ld_airbattle for combined fleet

---

src/library/modules/Meta.js

making KC3Meta.shipIcon and KC3Meta.abyssIcon the same

unify shipIcon and abyssIcon

---

src/library/modules/Kcsapi.js
src/library/modules/PoiDBSubmission.js
src/library/objects/Player.js

- Fix #1146 
- `select_rank` and `pass_event` support

PoiDBSubmission update

---

src/pages/popup/popup.css
src/pages/popup/popup.html
src/pages/popup/popup.js
update

implemented #973 
don't forget to change url of `update` file from branch `dev-server-mt-reminder` to `master`

Server maintenance time reminder on popup menu

---

src/library/objects/Ship.js
src/pages/strategy/tabs/docking/docking.css
src/pages/strategy/tabs/docking/docking.js

- code cleanup
- keep ship info sync-ed (don't have to refresh page)
- pink indicator when a ship is being repaired by akashi:

Improved docking tab

---

src/pages/strategy/tabs/docking/docking.js

when akashi repair time is the same, tiebreak by using docking time.
or when docking time is the same, tiebreak by akashi repair time.

docking: tiebreak docking time using the other timer

---

src/library/modules/Kcsapi.js

Solve #1170. Still needs verification.
@KC3Kai/testers could you test this patch? just keep an eye on daily / weekly / monthly sortie quests, everything should work as usual. the only difference would be that now defeating 4-4 boss should also count to Bw6 (Defeat 12 bosses in horned nodes in World 4)

Rework quest tracking

---

src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js

Add speed filter to ships tab of Strategy room

---

src/pages/strategy/tabs/expcalc/expcalc.js

should have done this looooong time ago.

leveling room Y/N color fix.

---

.travis.yml
package.json
src/library/injections/osapi.js
src/library/modules/Service.js
src/manifest.json
src/pages/game/api.css
src/pages/game/api.html
src/pages/game/api.js
src/pages/popup/popup.js
update

* TL repos for new items and quests in the latest update
* Hotfix for "Play via API Link", will stage new API features for another time
* Merging pull requests with "**release**" tag are uploaded to the webstore

Release 27.3

---

.travis.yml
package.json
src/library/modules/Kcsapi.js
src/manifest.json
src/pages/game/api.js
update

* Fix #1202 battle info fix for maps without gauges
* Refresh page after Forget/Update API Liks
* Auto-start API Links on DevTools

Release 27.4

---

package.json
src/library/modules/Meta.js
src/library/objects/Player.js
src/manifest.json
src/pages/game/api.js
src/pages/popup/popup.html
src/pages/strategy/tabs/profile/profile.html
src/pages/strategy/tabs/profile/profile.js
update

* Fix for unable to open KC3 menu / also fixes long time to open menu
* Use local donation button image, in case puush is inacessible for players
* Ability for translators to define localization for K2 -B, -C, Zwei and Drei
* #1206 API Page Reload Confirmation
* #1004 Rank Points: Reset 1hr before, End of month midnight cut-off, +ExOp bonus
* #1207 Manual Rank Point cut-off button

Release 27.5

---

src/library/modules/Kcsapi.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js

Hint by last comment of #1003
And also:
* Fix i18n miss for plain theme
* Fix quest tracking and map without gauge

Add ship name to tooltips on battle and PvP

---

Gruntfile.js
package.json
src/library/modules/Kcsapi.js
src/library/modules/Network.js
src/manifest.json
src/pages/strategy/tabs/mstship/mstship.js
update

* #1240 Fix jszip library missing from data backup
* #1226 NPC Subtitles
* Crack patch for cg API version
* Support new API call `api_get_member/require_info`
* rankPt+1 hotfix involving quest tracking
* [TH] Subtitle quotes
* [TCN] Subtitle quotes
* [KR] Subtitle quotes
* [JP] Subtitle quotes
* [EN] NPC Subtitles

Release 28.3

---

src/library/modules/Translation.js
src/pages/strategy/strategy.html
src/pages/strategy/tabs/translations/translations.css
src/pages/strategy/tabs/translations/translations.html
src/pages/strategy/tabs/translations/translations.js

Requires #1275 so I'm making PR on `dev-dev-only-tab` instead of the master.
A dev-only page for translators, missing items are colored in red xD.

Translation Previewer

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/Translation.js
src/pages/strategy/strategy.css
src/pages/strategy/strategy.html
src/pages/strategy/strategy.js
src/pages/strategy/tabs/playground/README.md
src/pages/strategy/tabs/playground/playground.css
src/pages/strategy/tabs/playground/playground.html
src/pages/strategy/tabs/playground/playground.js
src/pages/strategy/tabs/translations/translations.css
src/pages/strategy/tabs/translations/translations.html
src/pages/strategy/tabs/translations/translations.js

as described in #1270 
- submenu "Dev-Only" in strategy room. only visible when `SettingsDevOnlyPages` is turned on.
- a playground tab for developers to do experiments, see details in https://github.com/KC3Kai/KC3Kai/blob/dev-dev-only-tab/src/pages/strategy/tabs/playground/README.md

[dev-dev-only-tab] Developer-only tabs

---

src/library/modules/Master.js
src/library/modules/Translation.js
src/pages/strategy/strategy.html
src/pages/strategy/tabs/mstship/mstship.js
src/pages/strategy/tabs/quotes/quotes.css
src/pages/strategy/tabs/quotes/quotes.html
src/pages/strategy/tabs/quotes/quotes.js

a quick and dirty quote translation helper. feel free to tune the UI. 
left side list shows translation progress for each ships. green bar are those lines directly available, blue bars are inherited from previous remodels. gray bar are missing.
right side list shows voice lines for a specific ship. red background for missing quotes, blue background for inherited quotes, green background for those directly available.

Strategy room dev-only page: quotes helper

---

src/library/managers/GearManager.js

details are in code comments.
basically nothing is changed. just that when writing testcases, one should avoid putting itemId = 0 in GearManager.

minor fix to GearManager

---

src/library/modules/DataBackup.js
src/pages/strategy/tabs/databackup/databackup.js

[dev-databackup-2] Data Backup Update

---

src/library/modules/Kcsapi.js
src/library/modules/Master.js
src/library/modules/Network.js
src/library/modules/RemodelDb.js
src/library/modules/Translation.js
src/library/objects/Fleet.js
src/library/objects/Request.js

Close #1316
I think the features at #1249 is necessary for EN too :joy:  (related #1311)
so put it here.
And as I mentioned, suggest config for `grunt-remove-logging` task: keep console.`warn, error` methods may be better for error diagnosis :laughing:

Hotfix for quotes loading issue and logging #1316

---

src/pages/game/api.html
src/pages/game/dmm.js
src/pages/game/web.html
src/pages/game/web.js

Close #1316 
Issue reason see #1316 too, and as I mentioned, this required a test, towards the grunt built version before releasing to webstore. but my computer even have no npmjs installed :sweat_smile: 
Btw fix subtitles vanishing timing for play via frame mode... I even did not know it supports subtitles :sweat_smile:

Hotfix for website game issue #1316

---

src/library/modules/Kcsapi.js

[dev-quest-complete] Force complete quests on reward

---

src/library/modules/Meta.js
src/library/modules/Translation.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/game/api.js
src/pages/strategy/tabs/gears/gears.html
src/pages/strategy/tabs/gears/gears.js

Try to solve timers unexpected stopping related to #1279
Extra:
* Mute quotes looking up and transforming mass log
* Move quote looking up debug log to api.js
* Add new types 36 and 37 to gear tab of Strategy Room

Hotfix for unexpected timers stop issue #1279

---

src/pages/strategy/tabs/event/event.html

merge this during next maintenance xD

event history default to Spring 2016

---

src/library/managers/SortieManager.js
src/library/objects/Node.js

Disable rank prediction for long distance air battle node #1333

---

src/library/modules/Kcsapi.js
src/pages/strategy/tabs/gears/gears.html
src/pages/strategy/tabs/gears/gears.js

Fixes:
* Scraped or consumed gear not updated to local storage in time
Updates:
* Add support to check item from ship's ex-slot
* Add type 38 for new fighter

Update and fix Equipment List related

---

src/pages/strategy/tabs/expcalc/expcalc.css
src/pages/strategy/tabs/expcalc/expcalc.html
src/pages/strategy/tabs/expcalc/expcalc.js

UI tuned, enabling this feature again.

Goal template UI tuned

---

src/library/managers/ConfigManager.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js

Close #1369
Formula mode config and calculation logic is already there, just add click event to two themes.
ps. `air_formula` is not added to `settings.json`, so it's not able to be configured at settings page yet. should add it?

Toggle fighter power mode by clicking on panel

---

src/library/objects/Node.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.js

`api_itemget` API has changed to array from last game update.
update panel to display all resources if there are more than one array elements.

Support multi resources gaining node

---

src/library/objects/Fleet.js
src/library/objects/Ship.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js

accurate landing craft income bonus, according to formula found on wikia:
now T89 & T2 and improvement bonus are all taken into account.

Accurate landing craft bonus

---

src/library/modules/Kcsapi.js

support the new mechanic to swap equipment across ships

Support api_req_kaisou/slot_deprive

---

package.json
src/manifest.json
update

just update translations on webstore version

Release 30.3.1

---

src/pages/strategy/tabs/ships/ships.css
src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js

Color ship name indicator for fleets

---

src/library/objects/Gear.js
src/pages/devtools/themes/natsuiro/js/Shipbox.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/plain/js/Shipbox.js
src/pages/devtools/themes/plain/plain.css
src/pages/devtools/themes/plain/plain.html

close #1181
- take into account stars on carrier-based fighters
- show both improvement level and air proficiency
natsuiro:
plain:

fighter improvement update

---

src/pages/devtools/themes/natsuiro/js/Shipbox.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/plain/js/Shipbox.js
src/pages/devtools/themes/plain/plain.css
src/pages/devtools/themes/plain/plain.html

Close #1434
Continue to #1430
Feel free to do any adjustment.

Change air proficiency indicator and styles of panel

---

Gruntfile.js
package.json
src/data/developers.json
src/library/objects/Screenshot.js
src/manifest.json
src/pages/devtools/themes/natsuiro/js/Shipbox.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/plain/js/Shipbox.js
src/pages/devtools/themes/plain/plain.css
src/pages/devtools/themes/plain/plain.html
src/pages/game/dmm.js
update

* [Updated translations](https://github.com/KC3Kai/kc3-translations/commits/master)
* Fix #1434 Change air proficiency indicator and style (PR #1435 by @sinsinpub)
* Fix #1433 Taiha alert triggering on screenshot regardless of HP (`a678cdd` by @dragonjet)
* Fix #1437 Strategy Room > Library tab empty error (`a6a12f8` by @dragonjet)

Release 30.5.1

---

package.json
src/data/developers.json
src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/Kcsapi.js
src/library/modules/Translation.js
src/manifest.json
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/game/api.js
src/pages/popup/popup.html
src/pages/strategy/tabs/expcalc/expcalc.css
src/pages/strategy/tabs/expcalc/expcalc.js
src/pages/strategy/tabs/quotes/quotes.js
update

* [Updated translations](https://github.com/KC3Kai/kc3-translations/commits/master)
* `scn` quotes to aviod using special seasonal keys (`30cfa02` by @Javran)
* Highlight ships that are close to remodel or can be remodelled (PR #1441 by @DynamicSTOP)
* Added credits: @Xwilarg, @DynamicSTOP
* Fix #1440 Screenshot error: taihaStatus is not defined (`9bfe855` by @dragonjet)
* Menu > Changelog directs to PR list instead of outdated wiki (`3aaeae5` by @dragonjet)
* Close #345 Switch fleet view on formation change or equip (`fd15dde` by @dragonjet)

Release 30.5.2

---

package.json
src/data/developers.json
src/manifest.json
src/pages/strategy/strategy.css
src/pages/strategy/tabs/ships/ships.css
src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js
update

* [Updated translations](https://github.com/KC3Kai/kc3-translations/commits/master)
* #1443 About: nonsensed, fixed pictures in the credits page (`2703865` and `c09e897` by @dragonjet)
* #360 Ship List Update (PR #1448 by @dragonjet)
* Added sparkle filter
* Added show/hide pages
* Updated UI
* Filter list decluttered
* Equipment slot count no black circle
* "Back to top" button does not cover bottom ships

Release 30.5.4

---

.github/ISSUE_TEMPLATE.md

As already discussed with @dragonjet here is the proposed ISSUE_TEMPLATE markdown document. The template is somewhat in WIP but the basis is mostly there.
Source(s):
- https://github.com/blog/2111-issue-and-pull-request-templates

Create .github directory and ISSUE_TEMPLATE.md

---

src/library/objects/Gear.js

take into account improvment stat for fighter-bombers

---

src/library/modules/Database.js
src/library/objects/Node.js
src/pages/strategy/strategy.css
src/pages/strategy/strategy.html
src/pages/strategy/tabs/pvp/pvp.css
src/pages/strategy/tabs/pvp/pvp.html
src/pages/strategy/tabs/pvp/pvp.js

* Updated IndexedDB, +1 to webstore minor version (30.5.x -> 30.6.x)
* Strategy Room > PvP History
* Download Replay feature

[dev-pvp-history] PvP History

---

src/pages/strategy/tabs/badge/badge.css
src/pages/strategy/tabs/badge/badge.html
src/pages/strategy/tabs/badge/badge.js

as title says. just noticed the generator now supports traditional chinese so I updated the tab accordingly.

k2 badge generator traditional chinese support

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/objects/Screenshot.js
src/pages/settings/settings.html
src/pages/settings/settings.js

[dev-ss-quality] Screenshot image quality settings

---

src/library/managers/PlayerManager.js
src/library/managers/ShipManager.js
src/library/objects/Fleet.js
src/library/objects/Ship.js
src/pages/strategy/tabs/fleet/fleet.css
src/pages/strategy/tabs/fleet/fleet.html
src/pages/strategy/tabs/fleet/fleet.js

About #1367
DONE:
* Improved properties persistence
* Updated styles of fleets list; ex-slot, improvement, plane pro added
* Linking to other pages (depending on #1191)
TODO:
* Import from more data sources
* Any other accepted suggestion
Feel free to push commit to this branch.

[dev-fleet-viewer] Enhance Fleet Manager

---

src/library/modules/Kcsapi.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

Done:
* Replace messages with i18n terms
* Fix name changing decoding
* Fix stopped Exped faces refreshing

[dev-lbas-ui] LBAS i18n support

---

src/data/settings.json
src/library/objects/SettingsBox.js
src/pages/settings/settings.css

* Configurable Air Proficiency Values
* New settings types: `json`, `textarea`

Configurable Air Proficiency Values

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/managers/PlayerManager.js
src/library/managers/ShipManager.js
src/library/modules/Kcsapi.js
src/pages/devtools/themes/natsuiro/natsuiro.js

Fleet auto switching & HP indicator enhancement

---

src/library/managers/PlayerManager.js
src/library/objects/Ship.js
src/pages/strategy/tabs/docking/docking.js
src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js

new option to filter by whether the ship is capable of equipping daihatsu

ship list dahatsu filter

---

package.json
src/manifest.json
update

Translations updated:
* Urgent fixes for Korean translations (by @rephira)
* Updates for other languages
[See full list of commits in the translation repository](https://github.com/KC3Kai/kc3-translations/commits/master)
Thanks @sinsinpub and @dragonjet

Release 30.9.1 - minor TL fix

---

src/library/modules/PoiDBSubmission.js

data submission to https://github.com/poooi/poi-server with item drop support (e.g. saury)

PoiDBSubmission: recording item drop

---

package.json
src/manifest.json

HotRelease 30.9.5

---

src/library/modules/Translation.js

Quests translation unoverride `memo` attribute

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/pages/game/api.js
src/pages/game/dmm.js

Extra: remove quotes debug console logging.

An option to show ship name before each quotes of subtitle

---

src/library/objects/Fleet.js

now with Kinu K2 and Toku Daihatsu taken into account.
there's still a slight bit of inaccuracy, but it shouldn't matter.
(see comment in code for the technical explanation)

update expedition bonus calculation

---

src/library/modules/Network.js
src/library/modules/PoiDBSubmission.js

drop report for new APIs (abyssal combined fleet & both-combined fleet)

poi db submission update

---

src/library/managers/GearManager.js
src/library/managers/ShipManager.js
src/pages/devtools/themes/natsuiro/natsuiro.js

when moving over number of ships in devtools panel:
same goes with items.

Count number of heart-locked ships / items in devtools

---

src/library/objects/Fleet.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js

Updated to used latest formula, and show more detailed calculation.
Edit: require https://github.com/KC3Kai/kc3-translations/pull/345 for translations (currently only en and scn are available)

Expedition tab improvement: detailed income calculation

---

src/library/managers/PlayerManager.js
src/library/objects/Fleet.js
src/library/objects/Gear.js
src/library/objects/Ship.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/tabs/fleet/fleet.js

fix #1704. refactored a bit so each object handles its own structure of deckbuilder.

Fix deckbuilder

---

package.json
src/manifest.json
update

Previous merge [30.13.0](https://github.com/KC3Kai/KC3Kai/pull/1709) failed on webstore since I forgot to bump version

HotFix 30.13.1

---

src/pages/strategy/tabs/fleet/fleet.html
src/pages/strategy/tabs/fleet/fleet.js

reusing `.deckbuilder()` of KC3Fleet's

fleet manager: reuse .deckbuilder() method

---

package.json
src/manifest.json
src/pages/game/api.js
src/pages/game/dmm.js
update

non-urgent hotfix that contains KR fixes, and removal of chrome 55 warnings

HotFix 30.14.1

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/AntiAir.js
src/library/modules/Kcsapi.js
src/library/objects/Fleet.js
src/library/objects/Node.js
src/library/objects/SettingsBox.js
src/library/objects/Ship.js
src/pages/devtools/themes/natsuiro/js/Shipbox.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/tabs/fleet/fleet.css
src/pages/strategy/tabs/fleet/fleet.html
src/pages/strategy/tabs/fleet/fleet.js
src/pages/strategy/tabs/mstgear/mstgear.js
src/pages/strategy/tabs/mstship/mstship.css
src/pages/strategy/tabs/mstship/mstship.js
src/pages/strategy/tabs/pvp/pvp.html
src/pages/strategy/themes/dark.css
src/pages/strategy/themes/legacy.css

Continued for #1711 
Changelogs:
* Add fleet adjusted AA value to panel summary and Strategy Room Fleet Manager. Of course to get the space of AA column, all other columns become compact.
* Add AA Formation toggling to Settings and panel summary, use formation icon instead of AA icon
* Add imaginary enemy bomber slot to Settings. Which ship is selected to shoot at which bomber slot? God know.
* Adjust ship tool-tip of panel:
* Show ship adjusted AA value
* Show fixed shotdown range only if fleet AACI modifier available
* Ship fixed shotdown (range) affected by selected AA formation, and showing affected by which fleet AACI modifier
* Show ship AACI bonuses for both fixed and modifier values
* Show enemy bomber slot size and possible shotdown patterns based on it. Each pattern triggered …

Update UI to show more AA & AACI info

---

Gruntfile.js
package.json
src/manifest.json
src/pages/strategy/tabs/aircraft/aircraft.js
src/pages/strategy/tabs/akashi/akashi.js
src/pages/strategy/tabs/gears/gears.js
src/pages/strategy/themes/dark.css
update

⚓️  Urgent fix missing file in webstore build which mess up DMM frame / API mode
⚓️  Other minor fixes
* Fix checking of LBAS holding item
* Fix dark theme color of select/input control
⚓️  Update translations
btw: it's time to check if your extension is forced to auto-restart or not 😃

Hotfix 30.16.1

---

src/library/objects/Node.js

fix #1766 
most of the discussions are in the issue above too.

Fix battle rank

---

package.json
src/manifest.json
update

Release 30.16.2

---

src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js

Fix #1661
- also with some proper variable scoping.
- plain theme doesn't seem to actually using this feature, but the code
is exactly the same, so I have the same fix applied anyway
- at some point in future we should consider merging duplicated codes

fix "off by one" error for exp calculation

---

src/pages/strategy/tabs/badge/badge.css
src/pages/strategy/tabs/badge/badge.html
src/pages/strategy/tabs/badge/badge.js

attempt to fix #1781. need @KC3Kai/developers or @KC3Kai/testers for help because I don't have a chrome of version >=56.
- first make sure you can reproduce the bug mentioned above
- then if switching to `fix-badge` fixes it, please remove [`this`](https://github.com/KC3Kai/KC3Kai/blob/15e37e04d943b09be3231299deed3f7d027bfe70/src/pages/strategy/tabs/badge/badge.js#L140) line and commit for confirming it's working properly.

Fix badge generator export function

---

src/pages/strategy/tabs/expedtable/expedtable.css
src/pages/strategy/tabs/expedtable/expedtable.html
src/pages/strategy/tabs/expedtable/expedtable.js
src/pages/strategy/themes/dark.css
src/pages/strategy/themes/legacy.css

Expedition Table Interface

---

src/assets/js/steganography.js
src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/pvp/pvp.js

Close #1796.
Seems caused by change of chromium: Image element `complete` not determinable.
TODO: find the issue ticket of chromium on this.
Workaround:
* Update `steganography.js` to latest 1.0.2 from https://github.com/petereigenschink/steganography.js
* Hack `steganography.js`, use async callback instead after `onload` triggered
* Update PvP and Maps history, handle exception
* Tested on Chrome 54, Chromium 58 dev build

Fix replay not downloadable from chrome 57

---

package.json
src/manifest.json
src/pages/strategy/graphable.js
update

Fix strategy room is empty on webstore build.
For full information about the changes in Version 31, see following link:
https://github.com/KC3Kai/KC3Kai/pull/1789

HotFix 31.0.1

---

src/library/objects/ShowcaseExporter.js

Extracted some function parameters to global (row width\height)
Extracted colors to a single var (future templates?)

Fallback for new\missing ship and equip images

---

src/library/objects/ShowcaseExporter.js

Exporter: stripped ships from equip stat bonuses.

---

src/pages/strategy/tabs/shipdrop/shipdrop.js

I guess I get the ship drop infomation from edge_indexed to node_indexed

maybe fix the ship drop-record info problem in SR

---

src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/shipdrop/shipdrop.css
src/pages/strategy/tabs/shipdrop/shipdrop.html
src/pages/strategy/tabs/shipdrop/shipdrop.js
src/pages/strategy/themes/dark.css
src/pages/strategy/themes/legacy.css

a custom map UI of ship drop that imitates maps_page in SR

simple UI of ship drop

---

src/pages/strategy/tabs/badge/badge.html
src/pages/strategy/tabs/badge/badge.js

Following up on #1832. working with @Nya-chan to keep the badge generator updated.

badge generator location change

---

.travis.yml

see: https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies

try caching npm dependencies

---

src/library/objects/ShowcaseExporter.js
src/pages/strategy/tabs/showcase/showcase.html
src/pages/strategy/tabs/showcase/showcase.js

* modes:
1. Full (including non-heartlocked)
2. Standard (current)
3. Light (less info)
* saving settings to local storage (like on levelling page)
* heartlock alert (since it would mostly be used by new players they should be alerted)

showcase export modes

---

src/pages/devtools/themes/natsuiro/natsuiro.js

Show HP prediction of enemies in mouse-over

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/objects/SettingsBox.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/strategy.js

Full customisation of panel and strat room. Allow users to add own CSS on top of a theme in settings. 
[Strategy room example settings](http://i.imgur.com/mvEDFAr.png) / [Strategy room example](http://i.imgur.com/zptTp76.png)
Proposed TL diff, English isn't my native language so I'll let someone else do translation terms. Feel free to change titles or description.
```diff
diff --git a/data/en/terms.json b/data/en/terms.json
index 2156248..f0f7f44 100644
--- a/data/en/terms.json
+++ b/data/en/terms.json
@@ -338,6 +338,7 @@
"SettingsBGSizeDesc" : "See CSS background-size property",
"SettingsBGPosition" : "Background Position",
"SettingsBGPositionDesc" : "See CSS background-position property",
+	"SettingsCustomCSSDesc" : "Close and reopen panel box or reload strategy room page to see …
```

Add custom css setting for strategy room and panel box

---

update

Next maintenance scheduled for April 5, Wednesday

Update maintenance time

---

src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/event/event.html
src/pages/strategy/tabs/maps/maps.html
src/pages/strategy/tabs/pvp/pvp.html
src/pages/strategy/tabs/pvp/pvp.js

- Change shift-click to right click
- Add information about shift-clicking ability in help section
- Add rightclick exporting to PvP

Change shift-click replay export to right click + help + pvp

---

src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.js

Cumulative update

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/managers/PlayerManager.js
src/library/modules/Service.js
src/pages/devtools/themes/natsuiro/natsuiro.js

Added max Coin constant to PlayerManager

Improved hardcap warning & Added mobile notifications

---

src/library/objects/ShowcaseExporter.js

this is how split looks
and this is single line example
compared to how it was looking before

single line alignment and split for long words

---

src/library/managers/SortieManager.js
src/library/modules/Database.js
src/library/modules/ImageExport.js
src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/pvp/pvp.js
src/pages/strategy/tabs/screenshots/screenshots.css
src/pages/strategy/tabs/screenshots/screenshots.html
src/pages/strategy/tabs/screenshots/screenshots.js
src/pages/strategy/tabs/showcase/showcase.js

DONE
* Fix some issues left on #1948
* Update SRoom Screenshots page to manage all types of images uploaded to imgur.com
SS

Update screenshots management page

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/Service.js

See also #1970, credits to @FOG-Yamato
i'm not testing it personally... anyone who wanna test it, see the help page:  https://github.com/KC3Kai/KC3Kai/wiki/Settings%3A-PushNotifications

Push desktop notifications to mobile device via PushBullet

---

package.json
src/manifest.json
update

trying out the scheduled update for a change

updating for 31.5.0

---

Gruntfile.js
package.json
src/library/injections/dmm_takeover.js
src/manifest.json
update

Urgent fix the unchanged file names at #1890 and #1948
should be fixed this before following release 😂

Fix Gruntfile

---

package.json
src/manifest.json
update

just for update's sake. Hotfix PR coming soon

4th Anniversary lines 

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/Network.js
src/library/modules/OpenDBSubmission.js
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/plain/plain.html

Implement [OpenDB](http://swaytwig.com/opendb/) submitting. Submits equip dev, ship constructions, ship dropping and akashi improvements.
Based on PoiDB submissions code.

Add OpenDB submissions

---

src/library/managers/PlayerManager.js
src/library/modules/Database.js
src/library/modules/Kcsapi.js
src/library/objects/Player.js
src/pages/strategy/strategy.html
src/pages/strategy/tabs/experience/experience.css
src/pages/strategy/tabs/experience/experience.html
src/pages/strategy/tabs/experience/experience.js
src/pages/strategy/themes/dark.css

Using radio buttons instead of checkboxes unlike resources/consumables because scale of xp compared to level is huge.

Add experience/level history

---

src/library/objects/Player.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/tabs/profile/profile.js

Formatting will depend on user's browser's locale

Show ranking points to 1 decimal + format hq exp

---

package.json

To solve failures on recently chrome app uploading...

Upgrade grunt-webstore-upload

---

src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/event/event.css
src/pages/strategy/tabs/event/event.html
src/pages/strategy/tabs/maps/maps.css
src/pages/strategy/tabs/maps/maps.html

Adds combined fleet to sortie history pages (event & normal) and to replay images

Add combined fleet to sortie history and replay images

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/managers/SortieManager.js
src/library/modules/Database.js
src/library/objects/Node.js
src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/event/event.css
src/pages/strategy/tabs/maps/maps.css
tests/library/modules/BattlePrediction.js

Dark red means battle isn't in database (catbomb/refresh/crash/hasn't happened yet)

Log non-battle nodes for new sorties.

---

src/pages/strategy/tabs/maps/maps.css
src/pages/strategy/tabs/maps/maps.html

Copied event's double line code

Fix long sorties not showing all nodes

---

src/library/objects/ShowcaseExporter.js

ship count on the right of ship class
ship\gear count at the bottom along with total ship\gear cap

showcase export cap update

---

src/library/objects/ShowcaseExporter.js

crossed screws image in case player don't have Akashi yet

---

src/library/modules/OpenDBSubmission.js

Renamed `ship_dev` to `ship_build` and `equip_dev` to `equip_build`
Added `inventory` to `ship_drop`

Update OpenDB to new API

---

src/pages/strategy/tabs/fleet/fleet.css
src/pages/strategy/tabs/fleet/fleet.html
src/pages/strategy/tabs/fleet/fleet.js
src/pages/strategy/themes/dark.css
src/pages/strategy/themes/legacy.css

Allows more space for equips, related to #2273

Change fleet layout to a vertical one

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

Show previously encountered fleets to compass.
Might need some more css tweaks.

Add previously encountered abyssal fleets to battle activity

---

src/library/modules/OpenDBSubmission.js

Update OpenDB to new `api_ship_ke`

---

src/library/modules/BattlePrediction.js
src/library/modules/BattlePrediction/engagement/EngagementTypes.js
src/library/modules/BattlePrediction/engagement/Parsers.js
src/library/modules/BattlePrediction/phases/Raigeki.js
src/library/modules/BattlePrediction/phases/Util.js
src/library/modules/BattlePrediction/phases/Yasen.js
tests/library/modules/BattlePrediction/phases/Util.js

Battle Prediction bugfixes

---

src/library/managers/SortieManager.js
src/library/modules/BattlePrediction.js
src/library/modules/BattlePrediction/BattlePrediction.js
src/library/modules/BattlePrediction/engagement/EngagementTypes.js
src/library/modules/BattlePrediction/engagement/Parsers.js
src/library/modules/BattlePrediction/rank/AirRaid.js
src/library/modules/BattlePrediction/rank/Rank.js
src/library/modules/Kcsapi.js
src/library/objects/Node.js
tests/library/modules/BattlePrediction/rank/Rank.js

Night-to-day battle prediction support

---

src/library/objects/Node.js
src/pages/devtools/themes/default/horizontal/horizontal.js
src/pages/devtools/themes/default/vertical/vertical.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/sortielogs.js

Fix support tooltip and icon

---

src/library/managers/GearManager.js
src/library/modules/AntiAir.js

Added Suzutsuki and Suzutsuki Kai to AntiAir.js
Added Toukai (47) to GearManager.js to be recognized as LBAA

Updating library for new Akizuki-class DD and LBAA-type

---

src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/event/event.css
src/pages/strategy/tabs/event/event.html
src/pages/strategy/tabs/fleet/fleet.js

Fixes #2332 (and fixes #2369 if that's caused by this issue)

Add support for 7 ships in event history

---

package.json
src/library/managers/GearManager.js
src/library/modules/AntiAir.js
src/library/modules/BattlePrediction.js
src/library/modules/BattlePrediction/engagement/EngagementTypes.js
src/library/modules/PoiDBSubmission.js
src/library/objects/Node.js
src/manifest.json
src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/event/event.css
src/pages/strategy/tabs/event/event.html
src/pages/strategy/tabs/fleet/fleet.js
update

* [#2379](https://github.com/KC3Kai/KC3Kai/pull/2379) Support 7 ships fleet in strategy room pages ([#2332](https://github.com/KC3Kai/KC3Kai/issues/2332)) 
* Fix error while trying to download a replay image with the new 7 ships fleet ([#2369](https://github.com/KC3Kai/KC3Kai/issues/2369)) 
* [#2381](https://github.com/KC3Kai/KC3Kai/pull/2381) Update PoiDB Submission to support new API format
* [#2368](https://github.com/KC3Kai/KC3Kai/pull/2368) Fix LBAS raid damage calculation
* `en` items
* `en` quotes
* `th` quotes

Release 31.11.6

---

src/pages/devtools/themes/plain/plain.css
src/pages/devtools/themes/plain/plain.html
src/pages/devtools/themes/plain/plain.js

Fix plain theme not starting, add support for 7 ships to plain.

---

src/library/objects/Node.js
src/pages/devtools/themes/natsuiro/natsuiro.js

Fix air raid on non-battle nodes

---

src/pages/devtools/themes/natsuiro/natsuiro.js

Fix night support info

---

src/library/objects/Node.js

playerCombined is used to determine for combined fleets instead of isPlayerCombined
Addressing https://github.com/KC3Kai/KC3Kai/issues/2354

Fixed AACI shipname tooltip for combined fleet

---

src/library/objects/Fleet.js

Based rules from https://twitter.com/Lambda39/status/934719589740527617

Update support expedition estimation based on new criteria

---

src/pages/strategy/tabs/flowchart/flowchart.css
src/pages/strategy/tabs/flowchart/flowchart.html
src/pages/strategy/tabs/flowchart/flowchart.js
src/pages/strategy/themes/dark.css
src/pages/strategy/themes/legacy.css

Show completed one-time quests (with toggle)

---

src/library/modules/Database.js
src/pages/strategy/tabs/expedpast/expedpast.css
src/pages/strategy/tabs/expedpast/expedpast.html
src/pages/strategy/tabs/expedpast/expedpast.js

Add ability to filter by amount of sparkled ships
Shows GS rate for resulted filter.

Exped history: Filter by sparkles/show gs stats

---

src/library/modules/PoiDBSubmission.js

my screws out, not tested yet... i'll test it myself too, some details may need to be updated.
Report API see: https://github.com/poooi/poi-server/wiki

Report Akashi imrpovement recipes to poi-db

---

package.json
src/assets/js/global.js
src/library/modules/AntiAir.js
src/library/modules/Kcsapi.js
src/library/objects/Fleet.js
src/library/objects/Ship.js
src/manifest.json
src/pages/strategy/tabs/fleet/fleet.js
update

* Minor backend changes to get ready for 5th equipment slot
* `en` quests
* `en` quotes
* `id` quests
* `id` ships
* `id` terms
* `id` useitems
* `jp` quests
* `jp` quotes
* `ru` quests
* `ru` quotes
* `th` quotes
* `th` terms

Release 32.1.2

---

src/assets/js/global.js
src/library/managers/GearManager.js
src/library/managers/PlayerManager.js
src/library/modules/Kcsapi.js
src/library/modules/Network.js
src/library/modules/Translation.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

😂 Long time on this... I have no maxed equipment to test, please test and respond any suggestion.
DONE
* Add improvement recipe list activity
* Add improvement recipe detail activity
* Add improvement action result activity
* Rework on remodel_* API handling
* Add corresponding helper methods
SS
on Type 1 AP Shell, list and detail
on 10cm HA + AAFD result

Akashi improvement panel activities

---

package.json
src/library/managers/PlayerManager.js
src/library/modules/Kcsapi.js
src/library/objects/Player.js
src/library/objects/Ship.js
src/manifest.json
update

* Minor backend fixes
* `jp` quests

Hotfix 32.5.4

---

src/library/modules/TsunDBSubmission.js

Sorry for the trouble and being late
May need this field in case modifiers are different based on difficulty

Submit difficulty for unexpected damage (tsunDB)

---

misc/kcSHIPDATA.js
package.json
src/library/managers/SortieManager.js
src/library/modules/BattlePrediction.js
src/library/modules/BattlePrediction/phases/Friendly.js
src/library/modules/BattlePrediction/phases/Hougeki.js
src/library/modules/Kcsapi.js
src/library/modules/Master.js
src/library/modules/Meta.js
src/library/modules/Translation.js
src/library/objects/Gear.js
src/library/objects/Node.js
src/library/objects/Ship.js
src/manifest.json
src/pages/strategy/sortielogs.js
src/pages/strategy/tabs/mapmarkers/mapmarkers.js
src/pages/strategy/tabs/mstgear/mstgear.css
src/pages/strategy/tabs/mstgear/mstgear.html
src/pages/strategy/tabs/mstgear/mstgear.js
src/pages/strategy/tabs/mstship/mstship.js
src/pages/strategy/tabs/quotes/quotes.css
src/pages/strategy/tabs/quotes/quotes.html
src/pages/strategy/tabs/quotes/quotes.js
src/pages/strategy/themes/dark.css
update

* Show equippable ship types in the Equipment Library
* Update unexpected damage checking for Nelson Touch
* Update OASW conditions for CVE (`Shinyou`)
* Minor fixes
* `en` quotes
* `jp` quotes
* `kr` items
* `kr` quests
* `kr` quotes
* `ru` quotes
* `scn` quotes
* `th` quotes

Release 33.2.8

---

package.json
src/data/developers.json
src/library/modules/TsunDBSubmission.js
src/manifest.json
update

Hotfix 33.2.10

---

src/library/objects/ShowcaseExporter.js

Fix showcase ship sorter

---

.jshintrc
package.json
src/library/modules/AntiAir.js
src/library/modules/Kcsapi.js
src/library/modules/TsunDBSubmission.js
src/library/objects/Node.js
src/library/objects/Ship.js
src/library/objects/ShowcaseExporter.js
src/manifest.json
src/pages/devtools/themes/natsuiro/js/Shipbox.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/js/Shipbox.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/tabs/fleet/fleet.js
src/pages/strategy/tabs/locking/locking.css
update

* [#2686](https://github.com/KC3Kai/KC3Kai/pull/2686) Fix showcase ship sorter 
* If an enemy is sunk the HP bar will now be hidden on the panel
* Other minor fixes

Release 33.3.3

---

src/library/objects/Ship.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

Shows up like
Need some help with equip check logic
Thanks @DynamicSTOP for helping with boxes and layout
Made a typo with multiple equip count, whoops

Display equip bonus if new equip has bonus or is synergy gear

---

src/pages/strategy/tabs/showcase/showcase.css
src/pages/strategy/tabs/showcase/showcase.html
src/pages/strategy/tabs/showcase/showcase.js

moved it here instead of showcase page because
- showcase export button handlers looks too nice and i don't want to break those with ugly ifs
- item export isn't even started
- it's "alpha" and i don't want to mess with current "helping" processes too much, while ui still isn't polished

* export ships to kc3.moe

---

src/pages/strategy/tabs/expcalc/expcalc.html
src/pages/strategy/tabs/expcalc/expcalc.js

Add new ship order type for leveling tab

---

package.json
src/library/modules/TsunDBSubmission.js
src/library/objects/Gear.js
src/manifest.json
update

* Fix TsunDB Submission
* Minor Fixes

Hotfix 33.8.2

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/pages/devtools/themes/natsuiro/natsuiro.js

Refresh Reminder

---

src/pages/strategy/tabs/akashi/akashi.css
src/pages/strategy/tabs/akashi/akashi.html
src/pages/strategy/tabs/akashi/akashi.js
src/pages/strategy/tabs/blueprints/blueprints.html
src/pages/strategy/tabs/blueprints/blueprints.js
src/pages/strategy/tabs/gears/gears.css
src/pages/strategy/tabs/gears/gears.html
src/pages/strategy/tabs/gears/gears.js
src/pages/strategy/themes/dark.css

* akashi tab: equip personal sorting
* blueprints tab: new filter - completed
* equip tab: gear upgrade days

SR updates. Akashi, Equip and BP tabs

---

src/library/objects/Ship.js

Fletcher can OASW without condition. 😄

Update OASW condition

---

package.json
src/library/helpers/KanColleHelpers.js
src/library/managers/CalculatorManager.js
src/library/modules/Kcsapi.js
src/library/objects/Fleet.js
src/manifest.json
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/devtools/themes/plain/plain.js
src/pages/strategy/tabs/expedpast/expedpast.css
src/pages/strategy/tabs/expedpast/expedpast.html
src/pages/strategy/tabs/expedpast/expedpast.js
src/pages/strategy/tabs/fleet/fleet.js
src/pages/strategy/tabs/profile/profile.js
src/pages/strategy/themes/dark.css
update

* The `Fleet Manager` tab now shows total fleet stats, you can find it by mousing over the sum of the fleet levels
* It also shows the sum of total stats with and without improvements
* Update expedition stuff etc.
* Other minor fixes and improvements
* `de` quests
* `en` quests
* `en` quotes
* `en` quotes

Release 33.10.8

---

update

**Moonlight description updated 2019-08-15**. _The previous description was made on around March 18th. Sorry about that - it's my fault for not updating the description sooner. It's my intention to monitor feedback and make adjustments to the theme after release as my free time allows. -nonsensed_
_Bandwidth warning due to 4k resolution images in the links._
* PRs: [#2760](https://github.com/KC3Kai/KC3Kai/pull/2760), [#2777](https://github.com/KC3Kai/KC3Kai/pull/2777), [#2838](https://github.com/KC3Kai/KC3Kai/pull/2838) 
Moonlight features a slightly larger panel than Natsuiro, built specifically around supporting the new icon system and making some panel features provide a bit more information at a glance. It's designed more for people using higher resolution displays, but still works to …

Release 34.0.0

---

src/library/modules/TsunDBSubmission.js

Add TsunDB expedition submissions

Expedition TsunDB submissions

---

src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

Allow to toggle alert to avoid this https://youtu.be/wtZJOkW6YGU?t=785

Add button to pause/play taiha alert

---

src/library/modules/OpenDBSubmission.js

For https://github.com/KC3Kai/KC3Kai/issues/2933.

Fix OpenDB development submission

---

src/library/modules/AntiAir.js

"Fletcher-class" displays Fletcher

---

src/data/settings.json
src/library/managers/ConfigManager.js
src/library/modules/Kcsapi.js
src/library/modules/Network.js
src/pages/devtools/themes/natsuiro/natsuiro.css
src/pages/devtools/themes/natsuiro/natsuiro.html
src/pages/devtools/themes/natsuiro/natsuiro.js

Quest activity

---

package.json
src/library/helpers/KanColleHelpers.js
src/library/objects/Fleet.js
src/library/objects/Gear.js
src/library/objects/Ship.js
src/manifest.json
src/pages/devtools/themes/moonlight/moonlight.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/strategy/tabs/fleet/fleet.js
update

* Reworked Permissions for Chrome Webstore, Screenshotting may now require you to grant permission to the extension via opening the KC3 drop down menu in the browser toolbar. ([#2989](https://github.com/KC3Kai/KC3Kai/issues/2989))
* Please report any issues with these changes to our [issue tracker on github](https://github.com/KC3Kai/KC3Kai/issues). 
* ![81271409-9fd46f80-907e-11ea-942b-eac6d927a381](https://user-images.githubusercontent.com/5982780/81923185-5b724200-9631-11ea-9704-850c550766f3.png)
* Other minor fixes and improvements.

Release 34.6.1

---

package.json
src/assets/js/global.js
src/library/modules/DataBackup.js
src/library/modules/ImageExport.js
src/library/modules/Service.js
src/library/objects/Quest.js
src/manifest.json
src/pages/devtools/themes/moonlight/moonlight.js
src/pages/devtools/themes/natsuiro/natsuiro.js
src/pages/strategy/tabs/encounters/encounters.js
src/pages/strategy/tabs/mstship/mstship.js
src/pages/strategy/tabs/shipdrop/shipdrop.js
update

* Minor fixes and improvement
* Add some hotkeys to devtools panel:
* F8       - toggle mute
* Shift-F8 - toggle taiha sound
* F9       - screenshot
* 123456   - switch fleet view
* QWER     - switch activity tab

Release 34.8.6

---

.github/workflows/build.yml
.github/workflows/test.yml
package.json
src/data/settings.json
src/library/injections/dmm.css
src/library/managers/SortieManager.js
src/library/modules/TsunDBSubmission.js
src/library/objects/Gear.js
src/library/objects/Ship.js
src/manifest.json
src/pages/game/api.css
src/pages/strategy/tabs/ships/ships.css
src/pages/strategy/tabs/ships/ships.html
src/pages/strategy/tabs/ships/ships.js
update

* Minor fixes and improvements

Release 34.10.1

---

misc/wider-sroom.css
package.json
src/data/settings.json
src/library/injections/dmm_takeover.js
src/library/managers/ConfigManager.js
src/library/managers/SortieManager.js
src/library/modules/AntiAir.js
src/library/modules/Kcsapi.js
src/library/objects/Screenshot.js
src/library/objects/Ship.js
src/manifest.json
src/pages/strategy/tabs/blueprints/blueprints.css
src/pages/strategy/tabs/docking/docking.css
src/pages/strategy/tabs/docking/docking.html
src/pages/strategy/tabs/docking/docking.js
src/pages/strategy/tabs/locking/locking.css
src/pages/strategy/tabs/locking/locking.html
src/pages/strategy/tabs/locking/locking.js
src/pages/strategy/tabs/quotes/quotes.js
src/pages/strategy/tabs/shipquests/shipquests.css
src/pages/strategy/tabs/shipquests/shipquests.html
src/pages/strategy/tabs/ships/ships.css
src/pages/strategy/tabs/ships/ships.js
src/pages/strategy/themes/dark.css
src/pages/strategy/themes/legacy.css
update

* Minor fixes and improvements

Release 35.1.6

---

src/pages/strategy/tabs/profile/profile.html
src/pages/strategy/tabs/profile/profile.js

Add a button in the strategy room to export player ship list to CSV

Add CSV Ship List export

---

src/library/modules/TsunDBSubmission.js

See the descriptions of the commit messages.

Adding new maps in eventBattle submission and new fields in spAttack submission

---

src/data/quests_meta.json
src/library/managers/QuestManager.js
src/library/objects/Quest.js
src/pages/strategy/tabs/flowchart/flowchart.css
src/pages/strategy/tabs/flowchart/flowchart.html
src/pages/strategy/tabs/flowchart/flowchart.js

o) Update quest filter to use data from quest meta
o) Remove language dependency

Update quest filter to use data from quest meta
